// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

//lint:file-ignore SA5008 go-zero API types use non-standard json options.
package types

type BindAppPoliciesReq struct {
	Id         string   `path:"id"`
	PolicyKeys []string `json:"policy_keys"`
}

type CreateTenantAppReq struct {
	Id         string `path:"id"`
	Name       string `json:"name"`
	DailyQuota int64  `json:"daily_quota"`
	QpsLimit   int    `json:"qps_limit"`
}

type CreateTenantReq struct {
	Name string `json:"name"`
}

type Envelope struct {
	Code      int64       `json:"code"`
	Message   string      `json:"message"`
	Data      interface{} `json:"data,optional"`
	RequestID string      `json:"request_id,optional"`
}

type IssueGatewayTokenReq struct {
	TenantID string `json:"tenant_id"`
	AppID    string `json:"app_id"`
	TTL      int64  `json:"ttl"`
}

type GetTenantDetailReq struct {
	Id string `path:"id"`
}

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type PublishPolicyConfigReq struct {
	PolicyKey            string            `json:"policy_key"`
	DisplayName          string            `json:"display_name"`
	PublicMethod         string            `json:"public_method"`
	PublicPath           string            `json:"public_path"`
	UpstreamMethod       string            `json:"upstream_method"`
	UpstreamPath         string            `json:"upstream_path"`
	AllowedParams        []string          `json:"allowed_params,optional"`
	DeniedParams         []string          `json:"denied_params,optional"`
	DefaultParams        map[string]string `json:"default_params,optional"`
	ProviderCredentialID string            `json:"provider_credential_id"`
}

type UpdateAppQuotaReq struct {
	Id         string `path:"id"`
	DailyQuota int64  `json:"daily_quota"`
	QpsLimit   int    `json:"qps_limit"`
}

type UpdateAppStatusReq struct {
	Id     string `path:"id"`
	Status string `json:"status"`
}
