// Code generated by Codex based on scheduler.proto. DO NOT EDIT.

package schedulerservice

import (
	"context"

	"xsonar/pkg/proto/schedulerpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateTaskRequest   = schedulerpb.CreateTaskRequest
	GetTaskRequest      = schedulerpb.GetTaskRequest
	JsonResponse        = schedulerpb.JsonResponse
	ListTaskRunsRequest = schedulerpb.ListTaskRunsRequest

	SchedulerService interface {
		CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		ListTaskRuns(ctx context.Context, in *ListTaskRunsRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	}

	defaultSchedulerService struct {
		cli zrpc.Client
	}
)

// NewSchedulerService creates a typed scheduler RPC client wrapper.
func NewSchedulerService(cli zrpc.Client) SchedulerService {
	return &defaultSchedulerService{
		cli: cli,
	}
}

func (m *defaultSchedulerService) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := schedulerpb.NewSchedulerServiceClient(m.cli.Conn())
	return client.CreateTask(ctx, in, opts...)
}

func (m *defaultSchedulerService) GetTask(ctx context.Context, in *GetTaskRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := schedulerpb.NewSchedulerServiceClient(m.cli.Conn())
	return client.GetTask(ctx, in, opts...)
}

func (m *defaultSchedulerService) ListTaskRuns(ctx context.Context, in *ListTaskRunsRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := schedulerpb.NewSchedulerServiceClient(m.cli.Conn())
	return client.ListTaskRuns(ctx, in, opts...)
}
