// Code generated by Codex based on collectorworker.proto. DO NOT EDIT.

package collectorworkerservice

import (
	"context"

	"xsonar/pkg/proto/collectorworkerpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetWorkerStateRequest = collectorworkerpb.GetWorkerStateRequest
	JsonResponse          = collectorworkerpb.JsonResponse

	CollectorWorkerService interface {
		GetWorkerState(ctx context.Context, in *GetWorkerStateRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	}

	defaultCollectorWorkerService struct {
		cli zrpc.Client
	}
)

// NewCollectorWorkerService creates a typed collector worker RPC client wrapper.
func NewCollectorWorkerService(cli zrpc.Client) CollectorWorkerService {
	return &defaultCollectorWorkerService{
		cli: cli,
	}
}

func (m *defaultCollectorWorkerService) GetWorkerState(ctx context.Context, in *GetWorkerStateRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := collectorworkerpb.NewCollectorWorkerServiceClient(m.cli.Conn())
	return client.GetWorkerState(ctx, in, opts...)
}
