// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: apps/policy-rpc/policy.proto

package policypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DataJson      string                 `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonResponse) Reset() {
	*x = JsonResponse{}
	mi := &file_apps_policy_rpc_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResponse) ProtoMessage() {}

func (x *JsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_policy_rpc_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResponse.ProtoReflect.Descriptor instead.
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return file_apps_policy_rpc_policy_proto_rawDescGZIP(), []int{0}
}

func (x *JsonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JsonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JsonResponse) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type ResolvePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Path          string                 `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolvePolicyRequest) Reset() {
	*x = ResolvePolicyRequest{}
	mi := &file_apps_policy_rpc_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolvePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolvePolicyRequest) ProtoMessage() {}

func (x *ResolvePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_policy_rpc_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolvePolicyRequest.ProtoReflect.Descriptor instead.
func (*ResolvePolicyRequest) Descriptor() ([]byte, []int) {
	return file_apps_policy_rpc_policy_proto_rawDescGZIP(), []int{1}
}

func (x *ResolvePolicyRequest) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ResolvePolicyRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

type CheckAppPolicyAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	PolicyKey     string                 `protobuf:"bytes,2,opt,name=policy_key,json=policyKey,proto3" json:"policy_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAppPolicyAccessRequest) Reset() {
	*x = CheckAppPolicyAccessRequest{}
	mi := &file_apps_policy_rpc_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAppPolicyAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAppPolicyAccessRequest) ProtoMessage() {}

func (x *CheckAppPolicyAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_policy_rpc_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAppPolicyAccessRequest.ProtoReflect.Descriptor instead.
func (*CheckAppPolicyAccessRequest) Descriptor() ([]byte, []int) {
	return file_apps_policy_rpc_policy_proto_rawDescGZIP(), []int{2}
}

func (x *CheckAppPolicyAccessRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CheckAppPolicyAccessRequest) GetPolicyKey() string {
	if x != nil {
		return x.PolicyKey
	}
	return ""
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_apps_policy_rpc_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_policy_rpc_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_apps_policy_rpc_policy_proto_rawDescGZIP(), []int{3}
}

type PublishPolicyConfigRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	PolicyKey            string                 `protobuf:"bytes,1,opt,name=policy_key,json=policyKey,proto3" json:"policy_key,omitempty"`
	DisplayName          string                 `protobuf:"bytes,2,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	PublicMethod         string                 `protobuf:"bytes,3,opt,name=public_method,json=publicMethod,proto3" json:"public_method,omitempty"`
	PublicPath           string                 `protobuf:"bytes,4,opt,name=public_path,json=publicPath,proto3" json:"public_path,omitempty"`
	UpstreamMethod       string                 `protobuf:"bytes,5,opt,name=upstream_method,json=upstreamMethod,proto3" json:"upstream_method,omitempty"`
	UpstreamPath         string                 `protobuf:"bytes,6,opt,name=upstream_path,json=upstreamPath,proto3" json:"upstream_path,omitempty"`
	AllowedParams        []string               `protobuf:"bytes,7,rep,name=allowed_params,json=allowedParams,proto3" json:"allowed_params,omitempty"`
	DeniedParams         []string               `protobuf:"bytes,8,rep,name=denied_params,json=deniedParams,proto3" json:"denied_params,omitempty"`
	DefaultParams        map[string]string      `protobuf:"bytes,9,rep,name=default_params,json=defaultParams,proto3" json:"default_params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ProviderCredentialId string                 `protobuf:"bytes,10,opt,name=provider_credential_id,json=providerCredentialId,proto3" json:"provider_credential_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PublishPolicyConfigRequest) Reset() {
	*x = PublishPolicyConfigRequest{}
	mi := &file_apps_policy_rpc_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishPolicyConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishPolicyConfigRequest) ProtoMessage() {}

func (x *PublishPolicyConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_policy_rpc_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishPolicyConfigRequest.ProtoReflect.Descriptor instead.
func (*PublishPolicyConfigRequest) Descriptor() ([]byte, []int) {
	return file_apps_policy_rpc_policy_proto_rawDescGZIP(), []int{4}
}

func (x *PublishPolicyConfigRequest) GetPolicyKey() string {
	if x != nil {
		return x.PolicyKey
	}
	return ""
}

func (x *PublishPolicyConfigRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *PublishPolicyConfigRequest) GetPublicMethod() string {
	if x != nil {
		return x.PublicMethod
	}
	return ""
}

func (x *PublishPolicyConfigRequest) GetPublicPath() string {
	if x != nil {
		return x.PublicPath
	}
	return ""
}

func (x *PublishPolicyConfigRequest) GetUpstreamMethod() string {
	if x != nil {
		return x.UpstreamMethod
	}
	return ""
}

func (x *PublishPolicyConfigRequest) GetUpstreamPath() string {
	if x != nil {
		return x.UpstreamPath
	}
	return ""
}

func (x *PublishPolicyConfigRequest) GetAllowedParams() []string {
	if x != nil {
		return x.AllowedParams
	}
	return nil
}

func (x *PublishPolicyConfigRequest) GetDeniedParams() []string {
	if x != nil {
		return x.DeniedParams
	}
	return nil
}

func (x *PublishPolicyConfigRequest) GetDefaultParams() map[string]string {
	if x != nil {
		return x.DefaultParams
	}
	return nil
}

func (x *PublishPolicyConfigRequest) GetProviderCredentialId() string {
	if x != nil {
		return x.ProviderCredentialId
	}
	return ""
}

type BindAppPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	PolicyKeys    []string               `protobuf:"bytes,2,rep,name=policy_keys,json=policyKeys,proto3" json:"policy_keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BindAppPoliciesRequest) Reset() {
	*x = BindAppPoliciesRequest{}
	mi := &file_apps_policy_rpc_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BindAppPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BindAppPoliciesRequest) ProtoMessage() {}

func (x *BindAppPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_policy_rpc_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BindAppPoliciesRequest.ProtoReflect.Descriptor instead.
func (*BindAppPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_apps_policy_rpc_policy_proto_rawDescGZIP(), []int{5}
}

func (x *BindAppPoliciesRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *BindAppPoliciesRequest) GetPolicyKeys() []string {
	if x != nil {
		return x.PolicyKeys
	}
	return nil
}

var File_apps_policy_rpc_policy_proto protoreflect.FileDescriptor

const file_apps_policy_rpc_policy_proto_rawDesc = "" +
	"\n" +
	"\x1capps/policy-rpc/policy.proto\x12\x10xsonar.policy.v1\"Y\n" +
	"\fJsonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\tR\bdataJson\"B\n" +
	"\x14ResolvePolicyRequest\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\"S\n" +
	"\x1bCheckAppPolicyAccessRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"policy_key\x18\x02 \x01(\tR\tpolicyKey\"\x15\n" +
	"\x13ListPoliciesRequest\"\x9e\x04\n" +
	"\x1aPublishPolicyConfigRequest\x12\x1d\n" +
	"\n" +
	"policy_key\x18\x01 \x01(\tR\tpolicyKey\x12!\n" +
	"\fdisplay_name\x18\x02 \x01(\tR\vdisplayName\x12#\n" +
	"\rpublic_method\x18\x03 \x01(\tR\fpublicMethod\x12\x1f\n" +
	"\vpublic_path\x18\x04 \x01(\tR\n" +
	"publicPath\x12'\n" +
	"\x0fupstream_method\x18\x05 \x01(\tR\x0eupstreamMethod\x12#\n" +
	"\rupstream_path\x18\x06 \x01(\tR\fupstreamPath\x12%\n" +
	"\x0eallowed_params\x18\a \x03(\tR\rallowedParams\x12#\n" +
	"\rdenied_params\x18\b \x03(\tR\fdeniedParams\x12f\n" +
	"\x0edefault_params\x18\t \x03(\v2?.xsonar.policy.v1.PublishPolicyConfigRequest.DefaultParamsEntryR\rdefaultParams\x124\n" +
	"\x16provider_credential_id\x18\n" +
	" \x01(\tR\x14providerCredentialId\x1a@\n" +
	"\x12DefaultParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"P\n" +
	"\x16BindAppPoliciesRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1f\n" +
	"\vpolicy_keys\x18\x02 \x03(\tR\n" +
	"policyKeys2\xe8\x03\n" +
	"\rPolicyService\x12W\n" +
	"\rResolvePolicy\x12&.xsonar.policy.v1.ResolvePolicyRequest\x1a\x1e.xsonar.policy.v1.JsonResponse\x12e\n" +
	"\x14CheckAppPolicyAccess\x12-.xsonar.policy.v1.CheckAppPolicyAccessRequest\x1a\x1e.xsonar.policy.v1.JsonResponse\x12U\n" +
	"\fListPolicies\x12%.xsonar.policy.v1.ListPoliciesRequest\x1a\x1e.xsonar.policy.v1.JsonResponse\x12c\n" +
	"\x13PublishPolicyConfig\x12,.xsonar.policy.v1.PublishPolicyConfigRequest\x1a\x1e.xsonar.policy.v1.JsonResponse\x12[\n" +
	"\x0fBindAppPolicies\x12(.xsonar.policy.v1.BindAppPoliciesRequest\x1a\x1e.xsonar.policy.v1.JsonResponseB\x1bZ\x19xsonar/pkg/proto/policypbb\x06proto3"

var (
	file_apps_policy_rpc_policy_proto_rawDescOnce sync.Once
	file_apps_policy_rpc_policy_proto_rawDescData []byte
)

func file_apps_policy_rpc_policy_proto_rawDescGZIP() []byte {
	file_apps_policy_rpc_policy_proto_rawDescOnce.Do(func() {
		// #nosec G103 -- generated protobuf code uses unsafe in the protobuf runtime.
		file_apps_policy_rpc_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_policy_rpc_policy_proto_rawDesc), len(file_apps_policy_rpc_policy_proto_rawDesc)))
	})
	return file_apps_policy_rpc_policy_proto_rawDescData
}

var file_apps_policy_rpc_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_apps_policy_rpc_policy_proto_goTypes = []any{
	(*JsonResponse)(nil),                // 0: xsonar.policy.v1.JsonResponse
	(*ResolvePolicyRequest)(nil),        // 1: xsonar.policy.v1.ResolvePolicyRequest
	(*CheckAppPolicyAccessRequest)(nil), // 2: xsonar.policy.v1.CheckAppPolicyAccessRequest
	(*ListPoliciesRequest)(nil),         // 3: xsonar.policy.v1.ListPoliciesRequest
	(*PublishPolicyConfigRequest)(nil),  // 4: xsonar.policy.v1.PublishPolicyConfigRequest
	(*BindAppPoliciesRequest)(nil),      // 5: xsonar.policy.v1.BindAppPoliciesRequest
	nil,                                 // 6: xsonar.policy.v1.PublishPolicyConfigRequest.DefaultParamsEntry
}
var file_apps_policy_rpc_policy_proto_depIdxs = []int32{
	6, // 0: xsonar.policy.v1.PublishPolicyConfigRequest.default_params:type_name -> xsonar.policy.v1.PublishPolicyConfigRequest.DefaultParamsEntry
	1, // 1: xsonar.policy.v1.PolicyService.ResolvePolicy:input_type -> xsonar.policy.v1.ResolvePolicyRequest
	2, // 2: xsonar.policy.v1.PolicyService.CheckAppPolicyAccess:input_type -> xsonar.policy.v1.CheckAppPolicyAccessRequest
	3, // 3: xsonar.policy.v1.PolicyService.ListPolicies:input_type -> xsonar.policy.v1.ListPoliciesRequest
	4, // 4: xsonar.policy.v1.PolicyService.PublishPolicyConfig:input_type -> xsonar.policy.v1.PublishPolicyConfigRequest
	5, // 5: xsonar.policy.v1.PolicyService.BindAppPolicies:input_type -> xsonar.policy.v1.BindAppPoliciesRequest
	0, // 6: xsonar.policy.v1.PolicyService.ResolvePolicy:output_type -> xsonar.policy.v1.JsonResponse
	0, // 7: xsonar.policy.v1.PolicyService.CheckAppPolicyAccess:output_type -> xsonar.policy.v1.JsonResponse
	0, // 8: xsonar.policy.v1.PolicyService.ListPolicies:output_type -> xsonar.policy.v1.JsonResponse
	0, // 9: xsonar.policy.v1.PolicyService.PublishPolicyConfig:output_type -> xsonar.policy.v1.JsonResponse
	0, // 10: xsonar.policy.v1.PolicyService.BindAppPolicies:output_type -> xsonar.policy.v1.JsonResponse
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_apps_policy_rpc_policy_proto_init() }
func file_apps_policy_rpc_policy_proto_init() {
	if File_apps_policy_rpc_policy_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			// #nosec G103 -- generated protobuf code uses unsafe in the protobuf runtime.
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_policy_rpc_policy_proto_rawDesc), len(file_apps_policy_rpc_policy_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_policy_rpc_policy_proto_goTypes,
		DependencyIndexes: file_apps_policy_rpc_policy_proto_depIdxs,
		MessageInfos:      file_apps_policy_rpc_policy_proto_msgTypes,
	}.Build()
	File_apps_policy_rpc_policy_proto = out.File
	file_apps_policy_rpc_policy_proto_goTypes = nil
	file_apps_policy_rpc_policy_proto_depIdxs = nil
}
