// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: apps/policy-rpc/policy.proto

package policypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyService_ResolvePolicy_FullMethodName        = "/xsonar.policy.v1.PolicyService/ResolvePolicy"
	PolicyService_CheckAppPolicyAccess_FullMethodName = "/xsonar.policy.v1.PolicyService/CheckAppPolicyAccess"
	PolicyService_ListPolicies_FullMethodName         = "/xsonar.policy.v1.PolicyService/ListPolicies"
	PolicyService_PublishPolicyConfig_FullMethodName  = "/xsonar.policy.v1.PolicyService/PublishPolicyConfig"
	PolicyService_BindAppPolicies_FullMethodName      = "/xsonar.policy.v1.PolicyService/BindAppPolicies"
)

// PolicyServiceClient is the client API for PolicyService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyServiceClient interface {
	ResolvePolicy(ctx context.Context, in *ResolvePolicyRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	CheckAppPolicyAccess(ctx context.Context, in *CheckAppPolicyAccessRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	PublishPolicyConfig(ctx context.Context, in *PublishPolicyConfigRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	BindAppPolicies(ctx context.Context, in *BindAppPoliciesRequest, opts ...grpc.CallOption) (*JsonResponse, error)
}

type policyServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyServiceClient(cc grpc.ClientConnInterface) PolicyServiceClient {
	return &policyServiceClient{cc}
}

func (c *policyServiceClient) ResolvePolicy(ctx context.Context, in *ResolvePolicyRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, PolicyService_ResolvePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) CheckAppPolicyAccess(ctx context.Context, in *CheckAppPolicyAccessRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, PolicyService_CheckAppPolicyAccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, PolicyService_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) PublishPolicyConfig(ctx context.Context, in *PublishPolicyConfigRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, PolicyService_PublishPolicyConfig_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyServiceClient) BindAppPolicies(ctx context.Context, in *BindAppPoliciesRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, PolicyService_BindAppPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyServiceServer is the server API for PolicyService service.
// All implementations must embed UnimplementedPolicyServiceServer
// for forward compatibility.
type PolicyServiceServer interface {
	ResolvePolicy(context.Context, *ResolvePolicyRequest) (*JsonResponse, error)
	CheckAppPolicyAccess(context.Context, *CheckAppPolicyAccessRequest) (*JsonResponse, error)
	ListPolicies(context.Context, *ListPoliciesRequest) (*JsonResponse, error)
	PublishPolicyConfig(context.Context, *PublishPolicyConfigRequest) (*JsonResponse, error)
	BindAppPolicies(context.Context, *BindAppPoliciesRequest) (*JsonResponse, error)
	mustEmbedUnimplementedPolicyServiceServer()
}

// UnimplementedPolicyServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyServiceServer struct{}

func (UnimplementedPolicyServiceServer) ResolvePolicy(context.Context, *ResolvePolicyRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolvePolicy not implemented")
}
func (UnimplementedPolicyServiceServer) CheckAppPolicyAccess(context.Context, *CheckAppPolicyAccessRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckAppPolicyAccess not implemented")
}
func (UnimplementedPolicyServiceServer) ListPolicies(context.Context, *ListPoliciesRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedPolicyServiceServer) PublishPolicyConfig(context.Context, *PublishPolicyConfigRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishPolicyConfig not implemented")
}
func (UnimplementedPolicyServiceServer) BindAppPolicies(context.Context, *BindAppPoliciesRequest) (*JsonResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BindAppPolicies not implemented")
}
func (UnimplementedPolicyServiceServer) mustEmbedUnimplementedPolicyServiceServer() {}
func (UnimplementedPolicyServiceServer) testEmbeddedByValue()                       {}

// UnsafePolicyServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServiceServer will
// result in compilation errors.
type UnsafePolicyServiceServer interface {
	mustEmbedUnimplementedPolicyServiceServer()
}

func RegisterPolicyServiceServer(s grpc.ServiceRegistrar, srv PolicyServiceServer) {
	// If the following call pancis, it indicates UnimplementedPolicyServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyService_ServiceDesc, srv)
}

func _PolicyService_ResolvePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolvePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).ResolvePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_ResolvePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).ResolvePolicy(ctx, req.(*ResolvePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_CheckAppPolicyAccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAppPolicyAccessRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).CheckAppPolicyAccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_CheckAppPolicyAccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).CheckAppPolicyAccess(ctx, req.(*CheckAppPolicyAccessRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_PublishPolicyConfig_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishPolicyConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).PublishPolicyConfig(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_PublishPolicyConfig_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).PublishPolicyConfig(ctx, req.(*PublishPolicyConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PolicyService_BindAppPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindAppPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServiceServer).BindAppPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyService_BindAppPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServiceServer).BindAppPolicies(ctx, req.(*BindAppPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyService_ServiceDesc is the grpc.ServiceDesc for PolicyService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xsonar.policy.v1.PolicyService",
	HandlerType: (*PolicyServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolvePolicy",
			Handler:    _PolicyService_ResolvePolicy_Handler,
		},
		{
			MethodName: "CheckAppPolicyAccess",
			Handler:    _PolicyService_CheckAppPolicyAccess_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _PolicyService_ListPolicies_Handler,
		},
		{
			MethodName: "PublishPolicyConfig",
			Handler:    _PolicyService_PublishPolicyConfig_Handler,
		},
		{
			MethodName: "BindAppPolicies",
			Handler:    _PolicyService_BindAppPolicies_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/policy-rpc/policy.proto",
}
