// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: apps/scheduler-rpc/scheduler.proto

package schedulerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DataJson      string                 `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonResponse) Reset() {
	*x = JsonResponse{}
	mi := &file_apps_scheduler_rpc_scheduler_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResponse) ProtoMessage() {}

func (x *JsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_scheduler_rpc_scheduler_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResponse.ProtoReflect.Descriptor instead.
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return file_apps_scheduler_rpc_scheduler_proto_rawDescGZIP(), []int{0}
}

func (x *JsonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JsonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JsonResponse) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type CreateTaskRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	TaskType         string                 `protobuf:"bytes,2,opt,name=task_type,json=taskType,proto3" json:"task_type,omitempty"`
	Keyword          string                 `protobuf:"bytes,3,opt,name=keyword,proto3" json:"keyword,omitempty"`
	Priority         int32                  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	FrequencySeconds *int32                 `protobuf:"varint,5,opt,name=frequency_seconds,json=frequencySeconds,proto3,oneof" json:"frequency_seconds,omitempty"`
	// Provider-native boundary values stay caller-owned; these are intentionally strings.
	Since         string `protobuf:"bytes,6,opt,name=since,proto3" json:"since,omitempty"`
	Until         string `protobuf:"bytes,7,opt,name=until,proto3" json:"until,omitempty"`
	RequiredCount *int64 `protobuf:"varint,8,opt,name=required_count,json=requiredCount,proto3,oneof" json:"required_count,omitempty"`
	CreatedBy     string `protobuf:"bytes,9,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_apps_scheduler_rpc_scheduler_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_scheduler_rpc_scheduler_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_apps_scheduler_rpc_scheduler_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *CreateTaskRequest) GetTaskType() string {
	if x != nil {
		return x.TaskType
	}
	return ""
}

func (x *CreateTaskRequest) GetKeyword() string {
	if x != nil {
		return x.Keyword
	}
	return ""
}

func (x *CreateTaskRequest) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *CreateTaskRequest) GetFrequencySeconds() int32 {
	if x != nil && x.FrequencySeconds != nil {
		return *x.FrequencySeconds
	}
	return 0
}

func (x *CreateTaskRequest) GetSince() string {
	if x != nil {
		return x.Since
	}
	return ""
}

func (x *CreateTaskRequest) GetUntil() string {
	if x != nil {
		return x.Until
	}
	return ""
}

func (x *CreateTaskRequest) GetRequiredCount() int64 {
	if x != nil && x.RequiredCount != nil {
		return *x.RequiredCount
	}
	return 0
}

func (x *CreateTaskRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type GetTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTaskRequest) Reset() {
	*x = GetTaskRequest{}
	mi := &file_apps_scheduler_rpc_scheduler_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTaskRequest) ProtoMessage() {}

func (x *GetTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_scheduler_rpc_scheduler_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTaskRequest.ProtoReflect.Descriptor instead.
func (*GetTaskRequest) Descriptor() ([]byte, []int) {
	return file_apps_scheduler_rpc_scheduler_proto_rawDescGZIP(), []int{2}
}

func (x *GetTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type ListTaskRunsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTaskRunsRequest) Reset() {
	*x = ListTaskRunsRequest{}
	mi := &file_apps_scheduler_rpc_scheduler_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTaskRunsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTaskRunsRequest) ProtoMessage() {}

func (x *ListTaskRunsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_scheduler_rpc_scheduler_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTaskRunsRequest.ProtoReflect.Descriptor instead.
func (*ListTaskRunsRequest) Descriptor() ([]byte, []int) {
	return file_apps_scheduler_rpc_scheduler_proto_rawDescGZIP(), []int{3}
}

func (x *ListTaskRunsRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

var File_apps_scheduler_rpc_scheduler_proto protoreflect.FileDescriptor

const file_apps_scheduler_rpc_scheduler_proto_rawDesc = "" +
	"\n" +
	"\"apps/scheduler-rpc/scheduler.proto\x12\x13xsonar.scheduler.v1\"Y\n" +
	"\fJsonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\tR\bdataJson\"\xd1\x02\n" +
	"\x11CreateTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1b\n" +
	"\ttask_type\x18\x02 \x01(\tR\btaskType\x12\x18\n" +
	"\akeyword\x18\x03 \x01(\tR\akeyword\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\x05R\bpriority\x120\n" +
	"\x11frequency_seconds\x18\x05 \x01(\x05H\x00R\x10frequencySeconds\x88\x01\x01\x12\x14\n" +
	"\x05since\x18\x06 \x01(\tR\x05since\x12\x14\n" +
	"\x05until\x18\a \x01(\tR\x05until\x12*\n" +
	"\x0erequired_count\x18\b \x01(\x03H\x01R\rrequiredCount\x88\x01\x01\x12\x1d\n" +
	"\n" +
	"created_by\x18\t \x01(\tR\tcreatedByB\x14\n" +
	"\x12_frequency_secondsB\x11\n" +
	"\x0f_required_count\")\n" +
	"\x0eGetTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\".\n" +
	"\x13ListTaskRunsRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId2\x9b\x02\n" +
	"\x10SchedulerService\x12W\n" +
	"\n" +
	"CreateTask\x12&.xsonar.scheduler.v1.CreateTaskRequest\x1a!.xsonar.scheduler.v1.JsonResponse\x12Q\n" +
	"\aGetTask\x12#.xsonar.scheduler.v1.GetTaskRequest\x1a!.xsonar.scheduler.v1.JsonResponse\x12[\n" +
	"\fListTaskRuns\x12(.xsonar.scheduler.v1.ListTaskRunsRequest\x1a!.xsonar.scheduler.v1.JsonResponseB\x1eZ\x1cxsonar/pkg/proto/schedulerpbb\x06proto3"

var (
	file_apps_scheduler_rpc_scheduler_proto_rawDescOnce sync.Once
	file_apps_scheduler_rpc_scheduler_proto_rawDescData []byte
)

func file_apps_scheduler_rpc_scheduler_proto_rawDescGZIP() []byte {
	file_apps_scheduler_rpc_scheduler_proto_rawDescOnce.Do(func() {
		file_apps_scheduler_rpc_scheduler_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_scheduler_rpc_scheduler_proto_rawDesc), len(file_apps_scheduler_rpc_scheduler_proto_rawDesc)))
	})
	return file_apps_scheduler_rpc_scheduler_proto_rawDescData
}

var file_apps_scheduler_rpc_scheduler_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_apps_scheduler_rpc_scheduler_proto_goTypes = []any{
	(*JsonResponse)(nil),        // 0: xsonar.scheduler.v1.JsonResponse
	(*CreateTaskRequest)(nil),   // 1: xsonar.scheduler.v1.CreateTaskRequest
	(*GetTaskRequest)(nil),      // 2: xsonar.scheduler.v1.GetTaskRequest
	(*ListTaskRunsRequest)(nil), // 3: xsonar.scheduler.v1.ListTaskRunsRequest
}
var file_apps_scheduler_rpc_scheduler_proto_depIdxs = []int32{
	1, // 0: xsonar.scheduler.v1.SchedulerService.CreateTask:input_type -> xsonar.scheduler.v1.CreateTaskRequest
	2, // 1: xsonar.scheduler.v1.SchedulerService.GetTask:input_type -> xsonar.scheduler.v1.GetTaskRequest
	3, // 2: xsonar.scheduler.v1.SchedulerService.ListTaskRuns:input_type -> xsonar.scheduler.v1.ListTaskRunsRequest
	0, // 3: xsonar.scheduler.v1.SchedulerService.CreateTask:output_type -> xsonar.scheduler.v1.JsonResponse
	0, // 4: xsonar.scheduler.v1.SchedulerService.GetTask:output_type -> xsonar.scheduler.v1.JsonResponse
	0, // 5: xsonar.scheduler.v1.SchedulerService.ListTaskRuns:output_type -> xsonar.scheduler.v1.JsonResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_scheduler_rpc_scheduler_proto_init() }
func file_apps_scheduler_rpc_scheduler_proto_init() {
	if File_apps_scheduler_rpc_scheduler_proto != nil {
		return
	}
	file_apps_scheduler_rpc_scheduler_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_scheduler_rpc_scheduler_proto_rawDesc), len(file_apps_scheduler_rpc_scheduler_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_scheduler_rpc_scheduler_proto_goTypes,
		DependencyIndexes: file_apps_scheduler_rpc_scheduler_proto_depIdxs,
		MessageInfos:      file_apps_scheduler_rpc_scheduler_proto_msgTypes,
	}.Build()
	File_apps_scheduler_rpc_scheduler_proto = out.File
	file_apps_scheduler_rpc_scheduler_proto_goTypes = nil
	file_apps_scheduler_rpc_scheduler_proto_depIdxs = nil
}
