// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: access.proto

package server

import (
	"context"

	"xsonar/apps/access-rpc/internal/logic"
	"xsonar/apps/access-rpc/internal/svc"
	"xsonar/pkg/proto/accesspb"
)

type AccessServiceServer struct {
	svcCtx *svc.ServiceContext
	accesspb.UnimplementedAccessServiceServer
}

func NewAccessServiceServer(svcCtx *svc.ServiceContext) *AccessServiceServer {
	return &AccessServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *AccessServiceServer) GetAppAuthContext(ctx context.Context, in *accesspb.GetAppAuthContextRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewGetAppAuthContextLogic(ctx, s.svcCtx)
	return l.GetAppAuthContext(in)
}

func (s *AccessServiceServer) CheckReplay(ctx context.Context, in *accesspb.CheckReplayRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewCheckReplayLogic(ctx, s.svcCtx)
	return l.CheckReplay(in)
}

func (s *AccessServiceServer) CheckAndReserveQuota(ctx context.Context, in *accesspb.CheckAndReserveQuotaRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewCheckAndReserveQuotaLogic(ctx, s.svcCtx)
	return l.CheckAndReserveQuota(in)
}

func (s *AccessServiceServer) ReleaseQuotaOnFailure(ctx context.Context, in *accesspb.ReleaseQuotaOnFailureRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewReleaseQuotaOnFailureLogic(ctx, s.svcCtx)
	return l.ReleaseQuotaOnFailure(in)
}

func (s *AccessServiceServer) RecordUsageStat(ctx context.Context, in *accesspb.RecordUsageStatRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewRecordUsageStatLogic(ctx, s.svcCtx)
	return l.RecordUsageStat(in)
}

func (s *AccessServiceServer) QueryUsageStats(ctx context.Context, in *accesspb.QueryUsageStatsRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewQueryUsageStatsLogic(ctx, s.svcCtx)
	return l.QueryUsageStats(in)
}

func (s *AccessServiceServer) AuthenticateConsoleUser(ctx context.Context, in *accesspb.AuthenticateConsoleUserRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewAuthenticateConsoleUserLogic(ctx, s.svcCtx)
	return l.AuthenticateConsoleUser(in)
}

func (s *AccessServiceServer) CreateTenant(ctx context.Context, in *accesspb.CreateTenantRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewCreateTenantLogic(ctx, s.svcCtx)
	return l.CreateTenant(in)
}

func (s *AccessServiceServer) ListTenants(ctx context.Context, in *accesspb.ListTenantsRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewListTenantsLogic(ctx, s.svcCtx)
	return l.ListTenants(in)
}

func (s *AccessServiceServer) CreateTenantApp(ctx context.Context, in *accesspb.CreateTenantAppRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewCreateTenantAppLogic(ctx, s.svcCtx)
	return l.CreateTenantApp(in)
}

func (s *AccessServiceServer) ListTenantApps(ctx context.Context, in *accesspb.ListTenantAppsRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewListTenantAppsLogic(ctx, s.svcCtx)
	return l.ListTenantApps(in)
}

func (s *AccessServiceServer) RotateAppSecret(ctx context.Context, in *accesspb.RotateAppSecretRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewRotateAppSecretLogic(ctx, s.svcCtx)
	return l.RotateAppSecret(in)
}

func (s *AccessServiceServer) UpdateTenantAppStatus(ctx context.Context, in *accesspb.UpdateTenantAppStatusRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewUpdateTenantAppStatusLogic(ctx, s.svcCtx)
	return l.UpdateTenantAppStatus(in)
}

func (s *AccessServiceServer) UpdateAppQuota(ctx context.Context, in *accesspb.UpdateAppQuotaRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewUpdateAppQuotaLogic(ctx, s.svcCtx)
	return l.UpdateAppQuota(in)
}

func (s *AccessServiceServer) CheckIpBan(ctx context.Context, in *accesspb.CheckIpBanRequest) (*accesspb.JsonResponse, error) {
	l := logic.NewCheckIpBanLogic(ctx, s.svcCtx)
	return l.CheckIpBan(in)
}
