// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type Envelope struct {
	Code      int64       `json:"code"`
	Message   string      `json:"message"`
	Data      interface{} `json:"data,optional"`
	RequestID string      `json:"request_id,optional"`
}

type GatewayAuthReq struct {
	AppKey    string `form:"AppKey"`
	Timestamp string `form:"Timestamp"`
	Nonce     string `form:"Nonce"`
	Signature string `form:"Signature"`
}

type SearchTrendingReq struct {
	GatewayAuthReq
}

type SearchBoxReq struct {
	GatewayAuthReq
	Words      string `form:"words"`
	SearchType string `form:"searchType,optional"`
}

type SearchEntertainmentReq struct {
	GatewayAuthReq
}

type SearchExploreReq struct {
	GatewayAuthReq
}

type SearchNewsReq struct {
	GatewayAuthReq
}

type SearchSportsReq struct {
	GatewayAuthReq
}

type SearchTrendsReq struct {
	GatewayAuthReq
	ID string `form:"id"`
}

type SearchTweetsReq struct {
	GatewayAuthReq
	Words      string `form:"words"`
	Cursor     string `form:"cursor,optional"`
	Phrase     string `form:"phrase,optional"`
	Any        string `form:"any,optional"`
	None       string `form:"none,optional"`
	Tag        string `form:"tag,optional"`
	From       string `form:"from,optional"`
	To         string `form:"to,optional"`
	Mentioning string `form:"mentioning,optional"`
	Replies    string `form:"replies,optional"`
	Likes      string `form:"likes,optional"`
	Retweets   string `form:"retweets,optional"`
	Since      string `form:"since,optional"`
	Until      string `form:"until,optional"`
	Product    string `form:"product,optional"`
	Count      int64  `form:"count,optional"`
}

type TweetsByIDsReq struct {
	GatewayAuthReq
	TweetIDs string `form:"tweetIds"`
}

type TweetsBriefReq struct {
	GatewayAuthReq
	TweetID string `form:"tweetId"`
	Cursor  string `form:"cursor,optional"`
}

type TweetsDetailReq struct {
	GatewayAuthReq
	TweetID string `form:"tweetId"`
	Cursor  string `form:"cursor,optional"`
}

type TweetsFavoritersReq struct {
	GatewayAuthReq
	TweetID   string `form:"tweetId"`
	Cursor    string `form:"cursor,optional"`
	AuthToken string `form:"authToken,optional"`
}

type TweetsQuotesReq struct {
	GatewayAuthReq
	TweetID   string `form:"tweetId"`
	Cursor    string `form:"cursor,optional"`
	AuthToken string `form:"authToken,optional"`
}

type TweetsRepliesReq struct {
	GatewayAuthReq
	UserID string `form:"userId"`
	Cursor string `form:"cursor,optional"`
}

type TweetsRetweetersReq struct {
	GatewayAuthReq
	TweetID   string `form:"tweetId"`
	Cursor    string `form:"cursor,optional"`
	AuthToken string `form:"authToken,optional"`
}

type TweetsTimelineReq struct {
	GatewayAuthReq
	UserID string `form:"userId"`
	Cursor string `form:"cursor,optional"`
}

type CommunitiesReq struct {
	GatewayAuthReq
	ScreenName string `form:"screenName"`
}

type ListsReq struct {
	GatewayAuthReq
	UserID     string `form:"userId,optional"`
	ScreenName string `form:"screenName,optional"`
}

type UserByIDReq struct {
	GatewayAuthReq
	UserID string `form:"userId"`
	Cursor string `form:"cursor,optional"`
}

type UserByUsernameReq struct {
	GatewayAuthReq
	ScreenName string `form:"screenName"`
}

type UsersAccountAnalyticsReq struct {
	GatewayAuthReq
	RestID    string `form:"restId"`
	AuthToken string `form:"authToken"`
	CsrfToken string `form:"csrfToken,optional"`
}

type UsersArticlesTweetsReq struct {
	GatewayAuthReq
	UserID    string `form:"userId"`
	Cursor    string `form:"cursor,optional"`
	AuthToken string `form:"authToken,optional"`
}

type UsersByIDsReq struct {
	GatewayAuthReq
	UserIDs string `form:"userIds"`
}

type UsersFollowersReq struct {
	GatewayAuthReq
	UserID string `form:"userId"`
	Cursor string `form:"cursor,optional"`
}

type UsersFollowingsReq struct {
	GatewayAuthReq
	UserID string `form:"userId"`
	Cursor string `form:"cursor,optional"`
}

type UsersHighlightsReq struct {
	GatewayAuthReq
	UserID    string `form:"userId"`
	Cursor    string `form:"cursor,optional"`
	AuthToken string `form:"authToken,optional"`
}

type UsersLikesReq struct {
	GatewayAuthReq
	UserID    string `form:"userId"`
	Cursor    string `form:"cursor,optional"`
	AuthToken string `form:"authToken,optional"`
}

type UsersMentionsTimelineReq struct {
	GatewayAuthReq
	AuthToken       string `form:"authToken"`
	CsrfToken       string `form:"csrfToken,optional"`
	SinceID         string `form:"sinceId,optional"`
	MaxID           string `form:"maxId,optional"`
	IncludeEntities string `form:"includeEntities,optional"`
	TrimUser        string `form:"trimUser,optional"`
}

type UsersUsernameChangesReq struct {
	GatewayAuthReq
	ScreenName string `form:"screenName"`
}
