// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package types

type EmptyReq struct {
}

type Envelope struct {
	Code      int64       `json:"code"`
	Message   string      `json:"message"`
	Data      interface{} `json:"data,optional"`
	RequestID string      `json:"request_id,optional"`
}
