// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: apps/collector-worker-rpc/collectorworker.proto

package collectorworkerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DataJson      string                 `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonResponse) Reset() {
	*x = JsonResponse{}
	mi := &file_apps_collector_worker_rpc_collectorworker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResponse) ProtoMessage() {}

func (x *JsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_collector_worker_rpc_collectorworker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResponse.ProtoReflect.Descriptor instead.
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return file_apps_collector_worker_rpc_collectorworker_proto_rawDescGZIP(), []int{0}
}

func (x *JsonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JsonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JsonResponse) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type GetWorkerStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkerStateRequest) Reset() {
	*x = GetWorkerStateRequest{}
	mi := &file_apps_collector_worker_rpc_collectorworker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkerStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkerStateRequest) ProtoMessage() {}

func (x *GetWorkerStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_collector_worker_rpc_collectorworker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkerStateRequest.ProtoReflect.Descriptor instead.
func (*GetWorkerStateRequest) Descriptor() ([]byte, []int) {
	return file_apps_collector_worker_rpc_collectorworker_proto_rawDescGZIP(), []int{1}
}

func (x *GetWorkerStateRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

var File_apps_collector_worker_rpc_collectorworker_proto protoreflect.FileDescriptor

const file_apps_collector_worker_rpc_collectorworker_proto_rawDesc = "" +
	"\n" +
	"/apps/collector-worker-rpc/collectorworker.proto\x12\x19xsonar.collectorworker.v1\"Y\n" +
	"\fJsonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\tR\bdataJson\"4\n" +
	"\x15GetWorkerStateRequest\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId2\x85\x01\n" +
	"\x16CollectorWorkerService\x12k\n" +
	"\x0eGetWorkerState\x120.xsonar.collectorworker.v1.GetWorkerStateRequest\x1a'.xsonar.collectorworker.v1.JsonResponseB$Z\"xsonar/pkg/proto/collectorworkerpbb\x06proto3"

var (
	file_apps_collector_worker_rpc_collectorworker_proto_rawDescOnce sync.Once
	file_apps_collector_worker_rpc_collectorworker_proto_rawDescData []byte
)

func file_apps_collector_worker_rpc_collectorworker_proto_rawDescGZIP() []byte {
	file_apps_collector_worker_rpc_collectorworker_proto_rawDescOnce.Do(func() {
		// #nosec G103 -- generated protobuf code uses unsafe in the protobuf runtime.
		file_apps_collector_worker_rpc_collectorworker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_collector_worker_rpc_collectorworker_proto_rawDesc), len(file_apps_collector_worker_rpc_collectorworker_proto_rawDesc)))
	})
	return file_apps_collector_worker_rpc_collectorworker_proto_rawDescData
}

var file_apps_collector_worker_rpc_collectorworker_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_apps_collector_worker_rpc_collectorworker_proto_goTypes = []any{
	(*JsonResponse)(nil),          // 0: xsonar.collectorworker.v1.JsonResponse
	(*GetWorkerStateRequest)(nil), // 1: xsonar.collectorworker.v1.GetWorkerStateRequest
}
var file_apps_collector_worker_rpc_collectorworker_proto_depIdxs = []int32{
	1, // 0: xsonar.collectorworker.v1.CollectorWorkerService.GetWorkerState:input_type -> xsonar.collectorworker.v1.GetWorkerStateRequest
	0, // 1: xsonar.collectorworker.v1.CollectorWorkerService.GetWorkerState:output_type -> xsonar.collectorworker.v1.JsonResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_collector_worker_rpc_collectorworker_proto_init() }
func file_apps_collector_worker_rpc_collectorworker_proto_init() {
	if File_apps_collector_worker_rpc_collectorworker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			// #nosec G103 -- generated protobuf code uses unsafe in the protobuf runtime.
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_collector_worker_rpc_collectorworker_proto_rawDesc), len(file_apps_collector_worker_rpc_collectorworker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_collector_worker_rpc_collectorworker_proto_goTypes,
		DependencyIndexes: file_apps_collector_worker_rpc_collectorworker_proto_depIdxs,
		MessageInfos:      file_apps_collector_worker_rpc_collectorworker_proto_msgTypes,
	}.Build()
	File_apps_collector_worker_rpc_collectorworker_proto = out.File
	file_apps_collector_worker_rpc_collectorworker_proto_goTypes = nil
	file_apps_collector_worker_rpc_collectorworker_proto_depIdxs = nil
}
