// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: provider.proto

package server

import (
	"context"

	"xsonar/apps/provider-rpc/internal/logic"
	"xsonar/apps/provider-rpc/internal/svc"
	"xsonar/pkg/proto/providerpb"
)

type ProviderServiceServer struct {
	svcCtx *svc.ServiceContext
	providerpb.UnimplementedProviderServiceServer
}

func NewProviderServiceServer(svcCtx *svc.ServiceContext) *ProviderServiceServer {
	return &ProviderServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *ProviderServiceServer) ExecutePolicy(ctx context.Context, in *providerpb.ExecutePolicyRequest) (*providerpb.JsonResponse, error) {
	l := logic.NewExecutePolicyLogic(ctx, s.svcCtx)
	return l.ExecutePolicy(in)
}

func (s *ProviderServiceServer) HealthCheckProvider(ctx context.Context, in *providerpb.HealthCheckProviderRequest) (*providerpb.JsonResponse, error) {
	l := logic.NewHealthCheckProviderLogic(ctx, s.svcCtx)
	return l.HealthCheckProvider(in)
}
