// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: apps/provider-rpc/provider.proto

package providerpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DataJson      string                 `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonResponse) Reset() {
	*x = JsonResponse{}
	mi := &file_apps_provider_rpc_provider_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResponse) ProtoMessage() {}

func (x *JsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_provider_rpc_provider_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResponse.ProtoReflect.Descriptor instead.
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return file_apps_provider_rpc_provider_proto_rawDescGZIP(), []int{0}
}

func (x *JsonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JsonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JsonResponse) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type ExecutePolicyRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RequestId      string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	PolicyKey      string                 `protobuf:"bytes,2,opt,name=policy_key,json=policyKey,proto3" json:"policy_key,omitempty"`
	UpstreamMethod string                 `protobuf:"bytes,3,opt,name=upstream_method,json=upstreamMethod,proto3" json:"upstream_method,omitempty"`
	UpstreamPath   string                 `protobuf:"bytes,4,opt,name=upstream_path,json=upstreamPath,proto3" json:"upstream_path,omitempty"`
	QueryJson      string                 `protobuf:"bytes,5,opt,name=query_json,json=queryJson,proto3" json:"query_json,omitempty"`
	ProviderName   string                 `protobuf:"bytes,6,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ProviderApiKey string                 `protobuf:"bytes,7,opt,name=provider_api_key,json=providerApiKey,proto3" json:"provider_api_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecutePolicyRequest) Reset() {
	*x = ExecutePolicyRequest{}
	mi := &file_apps_provider_rpc_provider_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePolicyRequest) ProtoMessage() {}

func (x *ExecutePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_provider_rpc_provider_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePolicyRequest.ProtoReflect.Descriptor instead.
func (*ExecutePolicyRequest) Descriptor() ([]byte, []int) {
	return file_apps_provider_rpc_provider_proto_rawDescGZIP(), []int{1}
}

func (x *ExecutePolicyRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ExecutePolicyRequest) GetPolicyKey() string {
	if x != nil {
		return x.PolicyKey
	}
	return ""
}

func (x *ExecutePolicyRequest) GetUpstreamMethod() string {
	if x != nil {
		return x.UpstreamMethod
	}
	return ""
}

func (x *ExecutePolicyRequest) GetUpstreamPath() string {
	if x != nil {
		return x.UpstreamPath
	}
	return ""
}

func (x *ExecutePolicyRequest) GetQueryJson() string {
	if x != nil {
		return x.QueryJson
	}
	return ""
}

func (x *ExecutePolicyRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *ExecutePolicyRequest) GetProviderApiKey() string {
	if x != nil {
		return x.ProviderApiKey
	}
	return ""
}

type HealthCheckProviderRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckProviderRequest) Reset() {
	*x = HealthCheckProviderRequest{}
	mi := &file_apps_provider_rpc_provider_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckProviderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckProviderRequest) ProtoMessage() {}

func (x *HealthCheckProviderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_provider_rpc_provider_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckProviderRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckProviderRequest) Descriptor() ([]byte, []int) {
	return file_apps_provider_rpc_provider_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckProviderRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

var File_apps_provider_rpc_provider_proto protoreflect.FileDescriptor

const file_apps_provider_rpc_provider_proto_rawDesc = "" +
	"\n" +
	" apps/provider-rpc/provider.proto\x12\x12xsonar.provider.v1\"Y\n" +
	"\fJsonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\tR\bdataJson\"\x90\x02\n" +
	"\x14ExecutePolicyRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"policy_key\x18\x02 \x01(\tR\tpolicyKey\x12'\n" +
	"\x0fupstream_method\x18\x03 \x01(\tR\x0eupstreamMethod\x12#\n" +
	"\rupstream_path\x18\x04 \x01(\tR\fupstreamPath\x12\x1d\n" +
	"\n" +
	"query_json\x18\x05 \x01(\tR\tqueryJson\x12#\n" +
	"\rprovider_name\x18\x06 \x01(\tR\fproviderName\x12(\n" +
	"\x10provider_api_key\x18\a \x01(\tR\x0eproviderApiKey\"A\n" +
	"\x1aHealthCheckProviderRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName2\xd7\x01\n" +
	"\x0fProviderService\x12[\n" +
	"\rExecutePolicy\x12(.xsonar.provider.v1.ExecutePolicyRequest\x1a .xsonar.provider.v1.JsonResponse\x12g\n" +
	"\x13HealthCheckProvider\x12..xsonar.provider.v1.HealthCheckProviderRequest\x1a .xsonar.provider.v1.JsonResponseB\x1dZ\x1bxsonar/pkg/proto/providerpbb\x06proto3"

var (
	file_apps_provider_rpc_provider_proto_rawDescOnce sync.Once
	file_apps_provider_rpc_provider_proto_rawDescData []byte
)

func file_apps_provider_rpc_provider_proto_rawDescGZIP() []byte {
	file_apps_provider_rpc_provider_proto_rawDescOnce.Do(func() {
		// #nosec G103 -- generated protobuf code uses unsafe in the protobuf runtime.
		file_apps_provider_rpc_provider_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_provider_rpc_provider_proto_rawDesc), len(file_apps_provider_rpc_provider_proto_rawDesc)))
	})
	return file_apps_provider_rpc_provider_proto_rawDescData
}

var file_apps_provider_rpc_provider_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_apps_provider_rpc_provider_proto_goTypes = []any{
	(*JsonResponse)(nil),               // 0: xsonar.provider.v1.JsonResponse
	(*ExecutePolicyRequest)(nil),       // 1: xsonar.provider.v1.ExecutePolicyRequest
	(*HealthCheckProviderRequest)(nil), // 2: xsonar.provider.v1.HealthCheckProviderRequest
}
var file_apps_provider_rpc_provider_proto_depIdxs = []int32{
	1, // 0: xsonar.provider.v1.ProviderService.ExecutePolicy:input_type -> xsonar.provider.v1.ExecutePolicyRequest
	2, // 1: xsonar.provider.v1.ProviderService.HealthCheckProvider:input_type -> xsonar.provider.v1.HealthCheckProviderRequest
	0, // 2: xsonar.provider.v1.ProviderService.ExecutePolicy:output_type -> xsonar.provider.v1.JsonResponse
	0, // 3: xsonar.provider.v1.ProviderService.HealthCheckProvider:output_type -> xsonar.provider.v1.JsonResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_apps_provider_rpc_provider_proto_init() }
func file_apps_provider_rpc_provider_proto_init() {
	if File_apps_provider_rpc_provider_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			// #nosec G103 -- generated protobuf code uses unsafe in the protobuf runtime.
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_provider_rpc_provider_proto_rawDesc), len(file_apps_provider_rpc_provider_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_provider_rpc_provider_proto_goTypes,
		DependencyIndexes: file_apps_provider_rpc_provider_proto_depIdxs,
		MessageInfos:      file_apps_provider_rpc_provider_proto_msgTypes,
	}.Build()
	File_apps_provider_rpc_provider_proto = out.File
	file_apps_provider_rpc_provider_proto_goTypes = nil
	file_apps_provider_rpc_provider_proto_depIdxs = nil
}
