// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: policy.proto

package server

import (
	"context"

	"xsonar/apps/policy-rpc/internal/logic"
	"xsonar/apps/policy-rpc/internal/svc"
	"xsonar/pkg/proto/policypb"
)

type PolicyServiceServer struct {
	svcCtx *svc.ServiceContext
	policypb.UnimplementedPolicyServiceServer
}

func NewPolicyServiceServer(svcCtx *svc.ServiceContext) *PolicyServiceServer {
	return &PolicyServiceServer{
		svcCtx: svcCtx,
	}
}

func (s *PolicyServiceServer) ResolvePolicy(ctx context.Context, in *policypb.ResolvePolicyRequest) (*policypb.JsonResponse, error) {
	l := logic.NewResolvePolicyLogic(ctx, s.svcCtx)
	return l.ResolvePolicy(in)
}

func (s *PolicyServiceServer) CheckAppPolicyAccess(ctx context.Context, in *policypb.CheckAppPolicyAccessRequest) (*policypb.JsonResponse, error) {
	l := logic.NewCheckAppPolicyAccessLogic(ctx, s.svcCtx)
	return l.CheckAppPolicyAccess(in)
}

func (s *PolicyServiceServer) ListPolicies(ctx context.Context, in *policypb.ListPoliciesRequest) (*policypb.JsonResponse, error) {
	l := logic.NewListPoliciesLogic(ctx, s.svcCtx)
	return l.ListPolicies(in)
}

func (s *PolicyServiceServer) PublishPolicyConfig(ctx context.Context, in *policypb.PublishPolicyConfigRequest) (*policypb.JsonResponse, error) {
	l := logic.NewPublishPolicyConfigLogic(ctx, s.svcCtx)
	return l.PublishPolicyConfig(in)
}

func (s *PolicyServiceServer) BindAppPolicies(ctx context.Context, in *policypb.BindAppPoliciesRequest) (*policypb.JsonResponse, error) {
	l := logic.NewBindAppPoliciesLogic(ctx, s.svcCtx)
	return l.BindAppPolicies(in)
}
