// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.29.3
// source: apps/access-rpc/access.proto

package accesspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AccessService_GetAppAuthContext_FullMethodName       = "/xsonar.access.v1.AccessService/GetAppAuthContext"
	AccessService_GetAppAuthContextByID_FullMethodName   = "/xsonar.access.v1.AccessService/GetAppAuthContextByID"
	AccessService_CheckReplay_FullMethodName             = "/xsonar.access.v1.AccessService/CheckReplay"
	AccessService_CheckAndReserveQuota_FullMethodName    = "/xsonar.access.v1.AccessService/CheckAndReserveQuota"
	AccessService_ReleaseQuotaOnFailure_FullMethodName   = "/xsonar.access.v1.AccessService/ReleaseQuotaOnFailure"
	AccessService_RecordUsageStat_FullMethodName         = "/xsonar.access.v1.AccessService/RecordUsageStat"
	AccessService_QueryUsageStats_FullMethodName         = "/xsonar.access.v1.AccessService/QueryUsageStats"
	AccessService_AuthenticateConsoleUser_FullMethodName = "/xsonar.access.v1.AccessService/AuthenticateConsoleUser"
	AccessService_CreateTenant_FullMethodName            = "/xsonar.access.v1.AccessService/CreateTenant"
	AccessService_ListTenants_FullMethodName             = "/xsonar.access.v1.AccessService/ListTenants"
	AccessService_CreateTenantApp_FullMethodName         = "/xsonar.access.v1.AccessService/CreateTenantApp"
	AccessService_ListTenantApps_FullMethodName          = "/xsonar.access.v1.AccessService/ListTenantApps"
	AccessService_RotateAppSecret_FullMethodName         = "/xsonar.access.v1.AccessService/RotateAppSecret"
	AccessService_UpdateTenantAppStatus_FullMethodName   = "/xsonar.access.v1.AccessService/UpdateTenantAppStatus"
	AccessService_UpdateAppQuota_FullMethodName          = "/xsonar.access.v1.AccessService/UpdateAppQuota"
	AccessService_CheckIpBan_FullMethodName              = "/xsonar.access.v1.AccessService/CheckIpBan"
)

// AccessServiceClient is the client API for AccessService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AccessServiceClient interface {
	GetAppAuthContext(ctx context.Context, in *GetAppAuthContextRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	GetAppAuthContextByID(ctx context.Context, in *GetAppAuthContextByIDRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	CheckReplay(ctx context.Context, in *CheckReplayRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	CheckAndReserveQuota(ctx context.Context, in *CheckAndReserveQuotaRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	ReleaseQuotaOnFailure(ctx context.Context, in *ReleaseQuotaOnFailureRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	RecordUsageStat(ctx context.Context, in *RecordUsageStatRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	QueryUsageStats(ctx context.Context, in *QueryUsageStatsRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	AuthenticateConsoleUser(ctx context.Context, in *AuthenticateConsoleUserRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	CreateTenantApp(ctx context.Context, in *CreateTenantAppRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	ListTenantApps(ctx context.Context, in *ListTenantAppsRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	RotateAppSecret(ctx context.Context, in *RotateAppSecretRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	UpdateTenantAppStatus(ctx context.Context, in *UpdateTenantAppStatusRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	UpdateAppQuota(ctx context.Context, in *UpdateAppQuotaRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	CheckIpBan(ctx context.Context, in *CheckIpBanRequest, opts ...grpc.CallOption) (*JsonResponse, error)
}

type accessServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAccessServiceClient(cc grpc.ClientConnInterface) AccessServiceClient {
	return &accessServiceClient{cc}
}

func (c *accessServiceClient) GetAppAuthContext(ctx context.Context, in *GetAppAuthContextRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_GetAppAuthContext_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) GetAppAuthContextByID(ctx context.Context, in *GetAppAuthContextByIDRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_GetAppAuthContextByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) CheckReplay(ctx context.Context, in *CheckReplayRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_CheckReplay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) CheckAndReserveQuota(ctx context.Context, in *CheckAndReserveQuotaRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_CheckAndReserveQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) ReleaseQuotaOnFailure(ctx context.Context, in *ReleaseQuotaOnFailureRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_ReleaseQuotaOnFailure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) RecordUsageStat(ctx context.Context, in *RecordUsageStatRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_RecordUsageStat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) QueryUsageStats(ctx context.Context, in *QueryUsageStatsRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_QueryUsageStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) AuthenticateConsoleUser(ctx context.Context, in *AuthenticateConsoleUserRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_AuthenticateConsoleUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_ListTenants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) CreateTenantApp(ctx context.Context, in *CreateTenantAppRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_CreateTenantApp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) ListTenantApps(ctx context.Context, in *ListTenantAppsRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_ListTenantApps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) RotateAppSecret(ctx context.Context, in *RotateAppSecretRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_RotateAppSecret_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) UpdateTenantAppStatus(ctx context.Context, in *UpdateTenantAppStatusRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_UpdateTenantAppStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) UpdateAppQuota(ctx context.Context, in *UpdateAppQuotaRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_UpdateAppQuota_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *accessServiceClient) CheckIpBan(ctx context.Context, in *CheckIpBanRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JsonResponse)
	err := c.cc.Invoke(ctx, AccessService_CheckIpBan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AccessServiceServer is the server API for AccessService service.
// All implementations must embed UnimplementedAccessServiceServer
// for forward compatibility.
type AccessServiceServer interface {
	GetAppAuthContext(context.Context, *GetAppAuthContextRequest) (*JsonResponse, error)
	GetAppAuthContextByID(context.Context, *GetAppAuthContextByIDRequest) (*JsonResponse, error)
	CheckReplay(context.Context, *CheckReplayRequest) (*JsonResponse, error)
	CheckAndReserveQuota(context.Context, *CheckAndReserveQuotaRequest) (*JsonResponse, error)
	ReleaseQuotaOnFailure(context.Context, *ReleaseQuotaOnFailureRequest) (*JsonResponse, error)
	RecordUsageStat(context.Context, *RecordUsageStatRequest) (*JsonResponse, error)
	QueryUsageStats(context.Context, *QueryUsageStatsRequest) (*JsonResponse, error)
	AuthenticateConsoleUser(context.Context, *AuthenticateConsoleUserRequest) (*JsonResponse, error)
	CreateTenant(context.Context, *CreateTenantRequest) (*JsonResponse, error)
	ListTenants(context.Context, *ListTenantsRequest) (*JsonResponse, error)
	CreateTenantApp(context.Context, *CreateTenantAppRequest) (*JsonResponse, error)
	ListTenantApps(context.Context, *ListTenantAppsRequest) (*JsonResponse, error)
	RotateAppSecret(context.Context, *RotateAppSecretRequest) (*JsonResponse, error)
	UpdateTenantAppStatus(context.Context, *UpdateTenantAppStatusRequest) (*JsonResponse, error)
	UpdateAppQuota(context.Context, *UpdateAppQuotaRequest) (*JsonResponse, error)
	CheckIpBan(context.Context, *CheckIpBanRequest) (*JsonResponse, error)
	mustEmbedUnimplementedAccessServiceServer()
}

// UnimplementedAccessServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAccessServiceServer struct{}

func (UnimplementedAccessServiceServer) GetAppAuthContext(context.Context, *GetAppAuthContextRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppAuthContext not implemented")
}
func (UnimplementedAccessServiceServer) GetAppAuthContextByID(context.Context, *GetAppAuthContextByIDRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAppAuthContextByID not implemented")
}
func (UnimplementedAccessServiceServer) CheckReplay(context.Context, *CheckReplayRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckReplay not implemented")
}
func (UnimplementedAccessServiceServer) CheckAndReserveQuota(context.Context, *CheckAndReserveQuotaRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckAndReserveQuota not implemented")
}
func (UnimplementedAccessServiceServer) ReleaseQuotaOnFailure(context.Context, *ReleaseQuotaOnFailureRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseQuotaOnFailure not implemented")
}
func (UnimplementedAccessServiceServer) RecordUsageStat(context.Context, *RecordUsageStatRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordUsageStat not implemented")
}
func (UnimplementedAccessServiceServer) QueryUsageStats(context.Context, *QueryUsageStatsRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method QueryUsageStats not implemented")
}
func (UnimplementedAccessServiceServer) AuthenticateConsoleUser(context.Context, *AuthenticateConsoleUserRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AuthenticateConsoleUser not implemented")
}
func (UnimplementedAccessServiceServer) CreateTenant(context.Context, *CreateTenantRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedAccessServiceServer) ListTenants(context.Context, *ListTenantsRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedAccessServiceServer) CreateTenantApp(context.Context, *CreateTenantAppRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenantApp not implemented")
}
func (UnimplementedAccessServiceServer) ListTenantApps(context.Context, *ListTenantAppsRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenantApps not implemented")
}
func (UnimplementedAccessServiceServer) RotateAppSecret(context.Context, *RotateAppSecretRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateAppSecret not implemented")
}
func (UnimplementedAccessServiceServer) UpdateTenantAppStatus(context.Context, *UpdateTenantAppStatusRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateTenantAppStatus not implemented")
}
func (UnimplementedAccessServiceServer) UpdateAppQuota(context.Context, *UpdateAppQuotaRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAppQuota not implemented")
}
func (UnimplementedAccessServiceServer) CheckIpBan(context.Context, *CheckIpBanRequest) (*JsonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckIpBan not implemented")
}
func (UnimplementedAccessServiceServer) mustEmbedUnimplementedAccessServiceServer() {}
func (UnimplementedAccessServiceServer) testEmbeddedByValue()                       {}

// UnsafeAccessServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AccessServiceServer will
// result in compilation errors.
type UnsafeAccessServiceServer interface {
	mustEmbedUnimplementedAccessServiceServer()
}

func RegisterAccessServiceServer(s grpc.ServiceRegistrar, srv AccessServiceServer) {
	// If the following call panics, it indicates UnimplementedAccessServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AccessService_ServiceDesc, srv)
}

func _AccessService_GetAppAuthContext_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppAuthContextRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).GetAppAuthContext(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_GetAppAuthContext_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).GetAppAuthContext(ctx, req.(*GetAppAuthContextRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_GetAppAuthContextByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAppAuthContextByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).GetAppAuthContextByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_GetAppAuthContextByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).GetAppAuthContextByID(ctx, req.(*GetAppAuthContextByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_CheckReplay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckReplayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CheckReplay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CheckReplay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CheckReplay(ctx, req.(*CheckReplayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_CheckAndReserveQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckAndReserveQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CheckAndReserveQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CheckAndReserveQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CheckAndReserveQuota(ctx, req.(*CheckAndReserveQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_ReleaseQuotaOnFailure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseQuotaOnFailureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).ReleaseQuotaOnFailure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_ReleaseQuotaOnFailure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).ReleaseQuotaOnFailure(ctx, req.(*ReleaseQuotaOnFailureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_RecordUsageStat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordUsageStatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).RecordUsageStat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_RecordUsageStat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).RecordUsageStat(ctx, req.(*RecordUsageStatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_QueryUsageStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryUsageStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).QueryUsageStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_QueryUsageStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).QueryUsageStats(ctx, req.(*QueryUsageStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_AuthenticateConsoleUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateConsoleUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).AuthenticateConsoleUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_AuthenticateConsoleUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).AuthenticateConsoleUser(ctx, req.(*AuthenticateConsoleUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_ListTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).ListTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_ListTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).ListTenants(ctx, req.(*ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_CreateTenantApp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantAppRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CreateTenantApp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CreateTenantApp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CreateTenantApp(ctx, req.(*CreateTenantAppRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_ListTenantApps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantAppsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).ListTenantApps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_ListTenantApps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).ListTenantApps(ctx, req.(*ListTenantAppsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_RotateAppSecret_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateAppSecretRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).RotateAppSecret(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_RotateAppSecret_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).RotateAppSecret(ctx, req.(*RotateAppSecretRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_UpdateTenantAppStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateTenantAppStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).UpdateTenantAppStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_UpdateTenantAppStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).UpdateTenantAppStatus(ctx, req.(*UpdateTenantAppStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_UpdateAppQuota_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAppQuotaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).UpdateAppQuota(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_UpdateAppQuota_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).UpdateAppQuota(ctx, req.(*UpdateAppQuotaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AccessService_CheckIpBan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckIpBanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AccessServiceServer).CheckIpBan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AccessService_CheckIpBan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AccessServiceServer).CheckIpBan(ctx, req.(*CheckIpBanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AccessService_ServiceDesc is the grpc.ServiceDesc for AccessService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AccessService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xsonar.access.v1.AccessService",
	HandlerType: (*AccessServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAppAuthContext",
			Handler:    _AccessService_GetAppAuthContext_Handler,
		},
		{
			MethodName: "GetAppAuthContextByID",
			Handler:    _AccessService_GetAppAuthContextByID_Handler,
		},
		{
			MethodName: "CheckReplay",
			Handler:    _AccessService_CheckReplay_Handler,
		},
		{
			MethodName: "CheckAndReserveQuota",
			Handler:    _AccessService_CheckAndReserveQuota_Handler,
		},
		{
			MethodName: "ReleaseQuotaOnFailure",
			Handler:    _AccessService_ReleaseQuotaOnFailure_Handler,
		},
		{
			MethodName: "RecordUsageStat",
			Handler:    _AccessService_RecordUsageStat_Handler,
		},
		{
			MethodName: "QueryUsageStats",
			Handler:    _AccessService_QueryUsageStats_Handler,
		},
		{
			MethodName: "AuthenticateConsoleUser",
			Handler:    _AccessService_AuthenticateConsoleUser_Handler,
		},
		{
			MethodName: "CreateTenant",
			Handler:    _AccessService_CreateTenant_Handler,
		},
		{
			MethodName: "ListTenants",
			Handler:    _AccessService_ListTenants_Handler,
		},
		{
			MethodName: "CreateTenantApp",
			Handler:    _AccessService_CreateTenantApp_Handler,
		},
		{
			MethodName: "ListTenantApps",
			Handler:    _AccessService_ListTenantApps_Handler,
		},
		{
			MethodName: "RotateAppSecret",
			Handler:    _AccessService_RotateAppSecret_Handler,
		},
		{
			MethodName: "UpdateTenantAppStatus",
			Handler:    _AccessService_UpdateTenantAppStatus_Handler,
		},
		{
			MethodName: "UpdateAppQuota",
			Handler:    _AccessService_UpdateAppQuota_Handler,
		},
		{
			MethodName: "CheckIpBan",
			Handler:    _AccessService_CheckIpBan_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apps/access-rpc/access.proto",
}
