// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: apps/access-rpc/access.proto

package accesspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JsonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int32                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	DataJson      string                 `protobuf:"bytes,3,opt,name=data_json,json=dataJson,proto3" json:"data_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JsonResponse) Reset() {
	*x = JsonResponse{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JsonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JsonResponse) ProtoMessage() {}

func (x *JsonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JsonResponse.ProtoReflect.Descriptor instead.
func (*JsonResponse) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{0}
}

func (x *JsonResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *JsonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *JsonResponse) GetDataJson() string {
	if x != nil {
		return x.DataJson
	}
	return ""
}

type GetAppAuthContextRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppKey        string                 `protobuf:"bytes,1,opt,name=app_key,json=appKey,proto3" json:"app_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAppAuthContextRequest) Reset() {
	*x = GetAppAuthContextRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppAuthContextRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppAuthContextRequest) ProtoMessage() {}

func (x *GetAppAuthContextRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAppAuthContextRequest.ProtoReflect.Descriptor instead.
func (*GetAppAuthContextRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{1}
}

func (x *GetAppAuthContextRequest) GetAppKey() string {
	if x != nil {
		return x.AppKey
	}
	return ""
}

type CheckReplayRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Nonce         string                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckReplayRequest) Reset() {
	*x = CheckReplayRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckReplayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckReplayRequest) ProtoMessage() {}

func (x *CheckReplayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckReplayRequest.ProtoReflect.Descriptor instead.
func (*CheckReplayRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{2}
}

func (x *CheckReplayRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CheckReplayRequest) GetNonce() string {
	if x != nil {
		return x.Nonce
	}
	return ""
}

func (x *CheckReplayRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type CheckAndReserveQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	PolicyKey     string                 `protobuf:"bytes,2,opt,name=policy_key,json=policyKey,proto3" json:"policy_key,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckAndReserveQuotaRequest) Reset() {
	*x = CheckAndReserveQuotaRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckAndReserveQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckAndReserveQuotaRequest) ProtoMessage() {}

func (x *CheckAndReserveQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckAndReserveQuotaRequest.ProtoReflect.Descriptor instead.
func (*CheckAndReserveQuotaRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{3}
}

func (x *CheckAndReserveQuotaRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *CheckAndReserveQuotaRequest) GetPolicyKey() string {
	if x != nil {
		return x.PolicyKey
	}
	return ""
}

func (x *CheckAndReserveQuotaRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type ReleaseQuotaOnFailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseQuotaOnFailureRequest) Reset() {
	*x = ReleaseQuotaOnFailureRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseQuotaOnFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseQuotaOnFailureRequest) ProtoMessage() {}

func (x *ReleaseQuotaOnFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseQuotaOnFailureRequest.ProtoReflect.Descriptor instead.
func (*ReleaseQuotaOnFailureRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseQuotaOnFailureRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *ReleaseQuotaOnFailureRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

type RecordUsageStatRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TenantId           string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AppId              string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	PolicyKey          string                 `protobuf:"bytes,3,opt,name=policy_key,json=policyKey,proto3" json:"policy_key,omitempty"`
	RequestId          string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Success            bool                   `protobuf:"varint,5,opt,name=success,proto3" json:"success,omitempty"`
	DurationMs         int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	UpstreamDurationMs int64                  `protobuf:"varint,7,opt,name=upstream_duration_ms,json=upstreamDurationMs,proto3" json:"upstream_duration_ms,omitempty"`
	StatusCode         int32                  `protobuf:"varint,8,opt,name=status_code,json=statusCode,proto3" json:"status_code,omitempty"`
	ResultCode         string                 `protobuf:"bytes,9,opt,name=result_code,json=resultCode,proto3" json:"result_code,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecordUsageStatRequest) Reset() {
	*x = RecordUsageStatRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordUsageStatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordUsageStatRequest) ProtoMessage() {}

func (x *RecordUsageStatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordUsageStatRequest.ProtoReflect.Descriptor instead.
func (*RecordUsageStatRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{5}
}

func (x *RecordUsageStatRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RecordUsageStatRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *RecordUsageStatRequest) GetPolicyKey() string {
	if x != nil {
		return x.PolicyKey
	}
	return ""
}

func (x *RecordUsageStatRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *RecordUsageStatRequest) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RecordUsageStatRequest) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RecordUsageStatRequest) GetUpstreamDurationMs() int64 {
	if x != nil {
		return x.UpstreamDurationMs
	}
	return 0
}

func (x *RecordUsageStatRequest) GetStatusCode() int32 {
	if x != nil {
		return x.StatusCode
	}
	return 0
}

func (x *RecordUsageStatRequest) GetResultCode() string {
	if x != nil {
		return x.ResultCode
	}
	return ""
}

type QueryUsageStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	AppId         string                 `protobuf:"bytes,2,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	PolicyKey     string                 `protobuf:"bytes,3,opt,name=policy_key,json=policyKey,proto3" json:"policy_key,omitempty"`
	StartUnix     int64                  `protobuf:"varint,4,opt,name=start_unix,json=startUnix,proto3" json:"start_unix,omitempty"`
	EndUnix       int64                  `protobuf:"varint,5,opt,name=end_unix,json=endUnix,proto3" json:"end_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryUsageStatsRequest) Reset() {
	*x = QueryUsageStatsRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryUsageStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUsageStatsRequest) ProtoMessage() {}

func (x *QueryUsageStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUsageStatsRequest.ProtoReflect.Descriptor instead.
func (*QueryUsageStatsRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{6}
}

func (x *QueryUsageStatsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *QueryUsageStatsRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *QueryUsageStatsRequest) GetPolicyKey() string {
	if x != nil {
		return x.PolicyKey
	}
	return ""
}

func (x *QueryUsageStatsRequest) GetStartUnix() int64 {
	if x != nil {
		return x.StartUnix
	}
	return 0
}

func (x *QueryUsageStatsRequest) GetEndUnix() int64 {
	if x != nil {
		return x.EndUnix
	}
	return 0
}

type AuthenticateConsoleUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateConsoleUserRequest) Reset() {
	*x = AuthenticateConsoleUserRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateConsoleUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateConsoleUserRequest) ProtoMessage() {}

func (x *AuthenticateConsoleUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateConsoleUserRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateConsoleUserRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{7}
}

func (x *AuthenticateConsoleUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateConsoleUserRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

type CreateTenantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantRequest) Reset() {
	*x = CreateTenantRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantRequest) ProtoMessage() {}

func (x *CreateTenantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{8}
}

func (x *CreateTenantRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListTenantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantsRequest) Reset() {
	*x = ListTenantsRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantsRequest) ProtoMessage() {}

func (x *ListTenantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantsRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{9}
}

type CreateTenantAppRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	DailyQuota    int64                  `protobuf:"varint,3,opt,name=daily_quota,json=dailyQuota,proto3" json:"daily_quota,omitempty"`
	QpsLimit      int32                  `protobuf:"varint,4,opt,name=qps_limit,json=qpsLimit,proto3" json:"qps_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTenantAppRequest) Reset() {
	*x = CreateTenantAppRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTenantAppRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTenantAppRequest) ProtoMessage() {}

func (x *CreateTenantAppRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTenantAppRequest.ProtoReflect.Descriptor instead.
func (*CreateTenantAppRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{10}
}

func (x *CreateTenantAppRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateTenantAppRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateTenantAppRequest) GetDailyQuota() int64 {
	if x != nil {
		return x.DailyQuota
	}
	return 0
}

func (x *CreateTenantAppRequest) GetQpsLimit() int32 {
	if x != nil {
		return x.QpsLimit
	}
	return 0
}

type ListTenantAppsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTenantAppsRequest) Reset() {
	*x = ListTenantAppsRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTenantAppsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTenantAppsRequest) ProtoMessage() {}

func (x *ListTenantAppsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTenantAppsRequest.ProtoReflect.Descriptor instead.
func (*ListTenantAppsRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{11}
}

func (x *ListTenantAppsRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type RotateAppSecretRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateAppSecretRequest) Reset() {
	*x = RotateAppSecretRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateAppSecretRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateAppSecretRequest) ProtoMessage() {}

func (x *RotateAppSecretRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateAppSecretRequest.ProtoReflect.Descriptor instead.
func (*RotateAppSecretRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{12}
}

func (x *RotateAppSecretRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

type UpdateTenantAppStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateTenantAppStatusRequest) Reset() {
	*x = UpdateTenantAppStatusRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateTenantAppStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTenantAppStatusRequest) ProtoMessage() {}

func (x *UpdateTenantAppStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTenantAppStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateTenantAppStatusRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateTenantAppStatusRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UpdateTenantAppStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateAppQuotaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AppId         string                 `protobuf:"bytes,1,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	DailyQuota    int64                  `protobuf:"varint,2,opt,name=daily_quota,json=dailyQuota,proto3" json:"daily_quota,omitempty"`
	QpsLimit      int32                  `protobuf:"varint,3,opt,name=qps_limit,json=qpsLimit,proto3" json:"qps_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAppQuotaRequest) Reset() {
	*x = UpdateAppQuotaRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAppQuotaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAppQuotaRequest) ProtoMessage() {}

func (x *UpdateAppQuotaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAppQuotaRequest.ProtoReflect.Descriptor instead.
func (*UpdateAppQuotaRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateAppQuotaRequest) GetAppId() string {
	if x != nil {
		return x.AppId
	}
	return ""
}

func (x *UpdateAppQuotaRequest) GetDailyQuota() int64 {
	if x != nil {
		return x.DailyQuota
	}
	return 0
}

func (x *UpdateAppQuotaRequest) GetQpsLimit() int32 {
	if x != nil {
		return x.QpsLimit
	}
	return 0
}

type CheckIpBanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ip            string                 `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckIpBanRequest) Reset() {
	*x = CheckIpBanRequest{}
	mi := &file_apps_access_rpc_access_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckIpBanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckIpBanRequest) ProtoMessage() {}

func (x *CheckIpBanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_apps_access_rpc_access_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckIpBanRequest.ProtoReflect.Descriptor instead.
func (*CheckIpBanRequest) Descriptor() ([]byte, []int) {
	return file_apps_access_rpc_access_proto_rawDescGZIP(), []int{15}
}

func (x *CheckIpBanRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

var File_apps_access_rpc_access_proto protoreflect.FileDescriptor

const file_apps_access_rpc_access_proto_rawDesc = "" +
	"\n" +
	"\x1capps/access-rpc/access.proto\x12\x10xsonar.access.v1\"Y\n" +
	"\fJsonResponse\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x05R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1b\n" +
	"\tdata_json\x18\x03 \x01(\tR\bdataJson\"3\n" +
	"\x18GetAppAuthContextRequest\x12\x17\n" +
	"\aapp_key\x18\x01 \x01(\tR\x06appKey\"_\n" +
	"\x12CheckReplayRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\tR\x05nonce\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"r\n" +
	"\x1bCheckAndReserveQuotaRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"policy_key\x18\x02 \x01(\tR\tpolicyKey\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\"T\n" +
	"\x1cReleaseQuotaOnFailureRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\"\xb9\x02\n" +
	"\x16RecordUsageStatRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"policy_key\x18\x03 \x01(\tR\tpolicyKey\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\x12\x18\n" +
	"\asuccess\x18\x05 \x01(\bR\asuccess\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs\x120\n" +
	"\x14upstream_duration_ms\x18\a \x01(\x03R\x12upstreamDurationMs\x12\x1f\n" +
	"\vstatus_code\x18\b \x01(\x05R\n" +
	"statusCode\x12\x1f\n" +
	"\vresult_code\x18\t \x01(\tR\n" +
	"resultCode\"\xa5\x01\n" +
	"\x16QueryUsageStatsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x15\n" +
	"\x06app_id\x18\x02 \x01(\tR\x05appId\x12\x1d\n" +
	"\n" +
	"policy_key\x18\x03 \x01(\tR\tpolicyKey\x12\x1d\n" +
	"\n" +
	"start_unix\x18\x04 \x01(\x03R\tstartUnix\x12\x19\n" +
	"\bend_unix\x18\x05 \x01(\x03R\aendUnix\"X\n" +
	"\x1eAuthenticateConsoleUserRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\")\n" +
	"\x13CreateTenantRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x14\n" +
	"\x12ListTenantsRequest\"\x87\x01\n" +
	"\x16CreateTenantAppRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1f\n" +
	"\vdaily_quota\x18\x03 \x01(\x03R\n" +
	"dailyQuota\x12\x1b\n" +
	"\tqps_limit\x18\x04 \x01(\x05R\bqpsLimit\"4\n" +
	"\x15ListTenantAppsRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"/\n" +
	"\x16RotateAppSecretRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\"M\n" +
	"\x1cUpdateTenantAppStatusRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"l\n" +
	"\x15UpdateAppQuotaRequest\x12\x15\n" +
	"\x06app_id\x18\x01 \x01(\tR\x05appId\x12\x1f\n" +
	"\vdaily_quota\x18\x02 \x01(\x03R\n" +
	"dailyQuota\x12\x1b\n" +
	"\tqps_limit\x18\x03 \x01(\x05R\bqpsLimit\"#\n" +
	"\x11CheckIpBanRequest\x12\x0e\n" +
	"\x02ip\x18\x01 \x01(\tR\x02ip2\x94\v\n" +
	"\rAccessService\x12_\n" +
	"\x11GetAppAuthContext\x12*.xsonar.access.v1.GetAppAuthContextRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12S\n" +
	"\vCheckReplay\x12$.xsonar.access.v1.CheckReplayRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12e\n" +
	"\x14CheckAndReserveQuota\x12-.xsonar.access.v1.CheckAndReserveQuotaRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12g\n" +
	"\x15ReleaseQuotaOnFailure\x12..xsonar.access.v1.ReleaseQuotaOnFailureRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12[\n" +
	"\x0fRecordUsageStat\x12(.xsonar.access.v1.RecordUsageStatRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12[\n" +
	"\x0fQueryUsageStats\x12(.xsonar.access.v1.QueryUsageStatsRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12k\n" +
	"\x17AuthenticateConsoleUser\x120.xsonar.access.v1.AuthenticateConsoleUserRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12U\n" +
	"\fCreateTenant\x12%.xsonar.access.v1.CreateTenantRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12S\n" +
	"\vListTenants\x12$.xsonar.access.v1.ListTenantsRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12[\n" +
	"\x0fCreateTenantApp\x12(.xsonar.access.v1.CreateTenantAppRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12Y\n" +
	"\x0eListTenantApps\x12'.xsonar.access.v1.ListTenantAppsRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12[\n" +
	"\x0fRotateAppSecret\x12(.xsonar.access.v1.RotateAppSecretRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12g\n" +
	"\x15UpdateTenantAppStatus\x12..xsonar.access.v1.UpdateTenantAppStatusRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12Y\n" +
	"\x0eUpdateAppQuota\x12'.xsonar.access.v1.UpdateAppQuotaRequest\x1a\x1e.xsonar.access.v1.JsonResponse\x12Q\n" +
	"\n" +
	"CheckIpBan\x12#.xsonar.access.v1.CheckIpBanRequest\x1a\x1e.xsonar.access.v1.JsonResponseB\x1bZ\x19xsonar/pkg/proto/accesspbb\x06proto3"

var (
	file_apps_access_rpc_access_proto_rawDescOnce sync.Once
	file_apps_access_rpc_access_proto_rawDescData []byte
)

func file_apps_access_rpc_access_proto_rawDescGZIP() []byte {
	file_apps_access_rpc_access_proto_rawDescOnce.Do(func() {
		file_apps_access_rpc_access_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_apps_access_rpc_access_proto_rawDesc), len(file_apps_access_rpc_access_proto_rawDesc)))
	})
	return file_apps_access_rpc_access_proto_rawDescData
}

var file_apps_access_rpc_access_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_apps_access_rpc_access_proto_goTypes = []any{
	(*JsonResponse)(nil),                   // 0: xsonar.access.v1.JsonResponse
	(*GetAppAuthContextRequest)(nil),       // 1: xsonar.access.v1.GetAppAuthContextRequest
	(*CheckReplayRequest)(nil),             // 2: xsonar.access.v1.CheckReplayRequest
	(*CheckAndReserveQuotaRequest)(nil),    // 3: xsonar.access.v1.CheckAndReserveQuotaRequest
	(*ReleaseQuotaOnFailureRequest)(nil),   // 4: xsonar.access.v1.ReleaseQuotaOnFailureRequest
	(*RecordUsageStatRequest)(nil),         // 5: xsonar.access.v1.RecordUsageStatRequest
	(*QueryUsageStatsRequest)(nil),         // 6: xsonar.access.v1.QueryUsageStatsRequest
	(*AuthenticateConsoleUserRequest)(nil), // 7: xsonar.access.v1.AuthenticateConsoleUserRequest
	(*CreateTenantRequest)(nil),            // 8: xsonar.access.v1.CreateTenantRequest
	(*ListTenantsRequest)(nil),             // 9: xsonar.access.v1.ListTenantsRequest
	(*CreateTenantAppRequest)(nil),         // 10: xsonar.access.v1.CreateTenantAppRequest
	(*ListTenantAppsRequest)(nil),          // 11: xsonar.access.v1.ListTenantAppsRequest
	(*RotateAppSecretRequest)(nil),         // 12: xsonar.access.v1.RotateAppSecretRequest
	(*UpdateTenantAppStatusRequest)(nil),   // 13: xsonar.access.v1.UpdateTenantAppStatusRequest
	(*UpdateAppQuotaRequest)(nil),          // 14: xsonar.access.v1.UpdateAppQuotaRequest
	(*CheckIpBanRequest)(nil),              // 15: xsonar.access.v1.CheckIpBanRequest
}
var file_apps_access_rpc_access_proto_depIdxs = []int32{
	1,  // 0: xsonar.access.v1.AccessService.GetAppAuthContext:input_type -> xsonar.access.v1.GetAppAuthContextRequest
	2,  // 1: xsonar.access.v1.AccessService.CheckReplay:input_type -> xsonar.access.v1.CheckReplayRequest
	3,  // 2: xsonar.access.v1.AccessService.CheckAndReserveQuota:input_type -> xsonar.access.v1.CheckAndReserveQuotaRequest
	4,  // 3: xsonar.access.v1.AccessService.ReleaseQuotaOnFailure:input_type -> xsonar.access.v1.ReleaseQuotaOnFailureRequest
	5,  // 4: xsonar.access.v1.AccessService.RecordUsageStat:input_type -> xsonar.access.v1.RecordUsageStatRequest
	6,  // 5: xsonar.access.v1.AccessService.QueryUsageStats:input_type -> xsonar.access.v1.QueryUsageStatsRequest
	7,  // 6: xsonar.access.v1.AccessService.AuthenticateConsoleUser:input_type -> xsonar.access.v1.AuthenticateConsoleUserRequest
	8,  // 7: xsonar.access.v1.AccessService.CreateTenant:input_type -> xsonar.access.v1.CreateTenantRequest
	9,  // 8: xsonar.access.v1.AccessService.ListTenants:input_type -> xsonar.access.v1.ListTenantsRequest
	10, // 9: xsonar.access.v1.AccessService.CreateTenantApp:input_type -> xsonar.access.v1.CreateTenantAppRequest
	11, // 10: xsonar.access.v1.AccessService.ListTenantApps:input_type -> xsonar.access.v1.ListTenantAppsRequest
	12, // 11: xsonar.access.v1.AccessService.RotateAppSecret:input_type -> xsonar.access.v1.RotateAppSecretRequest
	13, // 12: xsonar.access.v1.AccessService.UpdateTenantAppStatus:input_type -> xsonar.access.v1.UpdateTenantAppStatusRequest
	14, // 13: xsonar.access.v1.AccessService.UpdateAppQuota:input_type -> xsonar.access.v1.UpdateAppQuotaRequest
	15, // 14: xsonar.access.v1.AccessService.CheckIpBan:input_type -> xsonar.access.v1.CheckIpBanRequest
	0,  // 15: xsonar.access.v1.AccessService.GetAppAuthContext:output_type -> xsonar.access.v1.JsonResponse
	0,  // 16: xsonar.access.v1.AccessService.CheckReplay:output_type -> xsonar.access.v1.JsonResponse
	0,  // 17: xsonar.access.v1.AccessService.CheckAndReserveQuota:output_type -> xsonar.access.v1.JsonResponse
	0,  // 18: xsonar.access.v1.AccessService.ReleaseQuotaOnFailure:output_type -> xsonar.access.v1.JsonResponse
	0,  // 19: xsonar.access.v1.AccessService.RecordUsageStat:output_type -> xsonar.access.v1.JsonResponse
	0,  // 20: xsonar.access.v1.AccessService.QueryUsageStats:output_type -> xsonar.access.v1.JsonResponse
	0,  // 21: xsonar.access.v1.AccessService.AuthenticateConsoleUser:output_type -> xsonar.access.v1.JsonResponse
	0,  // 22: xsonar.access.v1.AccessService.CreateTenant:output_type -> xsonar.access.v1.JsonResponse
	0,  // 23: xsonar.access.v1.AccessService.ListTenants:output_type -> xsonar.access.v1.JsonResponse
	0,  // 24: xsonar.access.v1.AccessService.CreateTenantApp:output_type -> xsonar.access.v1.JsonResponse
	0,  // 25: xsonar.access.v1.AccessService.ListTenantApps:output_type -> xsonar.access.v1.JsonResponse
	0,  // 26: xsonar.access.v1.AccessService.RotateAppSecret:output_type -> xsonar.access.v1.JsonResponse
	0,  // 27: xsonar.access.v1.AccessService.UpdateTenantAppStatus:output_type -> xsonar.access.v1.JsonResponse
	0,  // 28: xsonar.access.v1.AccessService.UpdateAppQuota:output_type -> xsonar.access.v1.JsonResponse
	0,  // 29: xsonar.access.v1.AccessService.CheckIpBan:output_type -> xsonar.access.v1.JsonResponse
	15, // [15:30] is the sub-list for method output_type
	0,  // [0:15] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_apps_access_rpc_access_proto_init() }
func file_apps_access_rpc_access_proto_init() {
	if File_apps_access_rpc_access_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_apps_access_rpc_access_proto_rawDesc), len(file_apps_access_rpc_access_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_apps_access_rpc_access_proto_goTypes,
		DependencyIndexes: file_apps_access_rpc_access_proto_depIdxs,
		MessageInfos:      file_apps_access_rpc_access_proto_msgTypes,
	}.Build()
	File_apps_access_rpc_access_proto = out.File
	file_apps_access_rpc_access_proto_goTypes = nil
	file_apps_access_rpc_access_proto_depIdxs = nil
}
