services:
  gateway-api:
    volumes:
      - ../../deploy/configs/local/gateway-api.yaml:/app/config/gateway-api.yaml:ro

  console-api:
    volumes:
      - ../../deploy/configs/local/console-api.yaml:/app/config/console-api.yaml:ro

  access-rpc:
    volumes:
      - ../../deploy/configs/local/access-rpc.yaml:/app/config/access-rpc.yaml:ro

  policy-rpc:
    volumes:
      - ../../deploy/configs/local/policy-rpc.yaml:/app/config/policy-rpc.yaml:ro

  provider-rpc:
    volumes:
      - ../../deploy/configs/local/provider-rpc.yaml:/app/config/provider-rpc.yaml:ro
