// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"xsonar/apps/console-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPut,
				Path:    "/admin/v1/apps/:id/policies",
				Handler: serverCtx.Bridge.HandleBindAppPolicies,
			},
			{
				Method:  http.MethodPut,
				Path:    "/admin/v1/apps/:id/quota",
				Handler: serverCtx.Bridge.HandleUpdateAppQuota,
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/v1/apps/:id/secret:rotate",
				Handler: serverCtx.Bridge.HandleRotateAppSecret,
			},
			{
				Method:  http.MethodPut,
				Path:    "/admin/v1/apps/:id/status",
				Handler: serverCtx.Bridge.HandleUpdateAppStatus,
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/v1/auth/login",
				Handler: serverCtx.Bridge.HandleLogin,
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/v1/gateway/token",
				Handler: serverCtx.Bridge.HandleIssueGatewayToken,
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/v1/health/services",
				Handler: serverCtx.Bridge.HandleServiceHealth,
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/v1/policies",
				Handler: serverCtx.Bridge.HandleListPolicies,
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/v1/policies",
				Handler: serverCtx.Bridge.HandlePublishPolicyConfig,
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/v1/reports/usage",
				Handler: serverCtx.Bridge.HandleUsageReport,
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/v1/tenants",
				Handler: serverCtx.Bridge.HandleListTenants,
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/v1/tenants",
				Handler: serverCtx.Bridge.HandleCreateTenant,
			},
			{
				Method:  http.MethodGet,
				Path:    "/admin/v1/tenants/:id",
				Handler: serverCtx.Bridge.HandleGetTenantDetail,
			},
			{
				Method:  http.MethodPost,
				Path:    "/admin/v1/tenants/:id/apps",
				Handler: serverCtx.Bridge.HandleCreateTenantApp,
			},
		},
	)
}
