// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: access.proto

package accessservice

import (
	"context"

	"xsonar/pkg/proto/accesspb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	AuthenticateConsoleUserRequest = accesspb.AuthenticateConsoleUserRequest
	CheckAndReserveQuotaRequest    = accesspb.CheckAndReserveQuotaRequest
	CheckIpBanRequest              = accesspb.CheckIpBanRequest
	CheckReplayRequest             = accesspb.CheckReplayRequest
	CreateTenantAppRequest         = accesspb.CreateTenantAppRequest
	CreateTenantRequest            = accesspb.CreateTenantRequest
	GetAppAuthContextRequest       = accesspb.GetAppAuthContextRequest
	JsonResponse                   = accesspb.JsonResponse
	ListTenantAppsRequest          = accesspb.ListTenantAppsRequest
	ListTenantsRequest             = accesspb.ListTenantsRequest
	QueryUsageStatsRequest         = accesspb.QueryUsageStatsRequest
	RecordUsageStatRequest         = accesspb.RecordUsageStatRequest
	ReleaseQuotaOnFailureRequest   = accesspb.ReleaseQuotaOnFailureRequest
	RotateAppSecretRequest         = accesspb.RotateAppSecretRequest
	UpdateAppQuotaRequest          = accesspb.UpdateAppQuotaRequest
	UpdateTenantAppStatusRequest   = accesspb.UpdateTenantAppStatusRequest

	AccessService interface {
		GetAppAuthContext(ctx context.Context, in *GetAppAuthContextRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		CheckReplay(ctx context.Context, in *CheckReplayRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		CheckAndReserveQuota(ctx context.Context, in *CheckAndReserveQuotaRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		ReleaseQuotaOnFailure(ctx context.Context, in *ReleaseQuotaOnFailureRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		RecordUsageStat(ctx context.Context, in *RecordUsageStatRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		QueryUsageStats(ctx context.Context, in *QueryUsageStatsRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		AuthenticateConsoleUser(ctx context.Context, in *AuthenticateConsoleUserRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		CreateTenantApp(ctx context.Context, in *CreateTenantAppRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		ListTenantApps(ctx context.Context, in *ListTenantAppsRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		RotateAppSecret(ctx context.Context, in *RotateAppSecretRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		UpdateTenantAppStatus(ctx context.Context, in *UpdateTenantAppStatusRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		UpdateAppQuota(ctx context.Context, in *UpdateAppQuotaRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		CheckIpBan(ctx context.Context, in *CheckIpBanRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	}

	defaultAccessService struct {
		cli zrpc.Client
	}
)

func NewAccessService(cli zrpc.Client) AccessService {
	return &defaultAccessService{
		cli: cli,
	}
}

func (m *defaultAccessService) GetAppAuthContext(ctx context.Context, in *GetAppAuthContextRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.GetAppAuthContext(ctx, in, opts...)
}

func (m *defaultAccessService) CheckReplay(ctx context.Context, in *CheckReplayRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.CheckReplay(ctx, in, opts...)
}

func (m *defaultAccessService) CheckAndReserveQuota(ctx context.Context, in *CheckAndReserveQuotaRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.CheckAndReserveQuota(ctx, in, opts...)
}

func (m *defaultAccessService) ReleaseQuotaOnFailure(ctx context.Context, in *ReleaseQuotaOnFailureRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.ReleaseQuotaOnFailure(ctx, in, opts...)
}

func (m *defaultAccessService) RecordUsageStat(ctx context.Context, in *RecordUsageStatRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.RecordUsageStat(ctx, in, opts...)
}

func (m *defaultAccessService) QueryUsageStats(ctx context.Context, in *QueryUsageStatsRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.QueryUsageStats(ctx, in, opts...)
}

func (m *defaultAccessService) AuthenticateConsoleUser(ctx context.Context, in *AuthenticateConsoleUserRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.AuthenticateConsoleUser(ctx, in, opts...)
}

func (m *defaultAccessService) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.CreateTenant(ctx, in, opts...)
}

func (m *defaultAccessService) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.ListTenants(ctx, in, opts...)
}

func (m *defaultAccessService) CreateTenantApp(ctx context.Context, in *CreateTenantAppRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.CreateTenantApp(ctx, in, opts...)
}

func (m *defaultAccessService) ListTenantApps(ctx context.Context, in *ListTenantAppsRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.ListTenantApps(ctx, in, opts...)
}

func (m *defaultAccessService) RotateAppSecret(ctx context.Context, in *RotateAppSecretRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.RotateAppSecret(ctx, in, opts...)
}

func (m *defaultAccessService) UpdateTenantAppStatus(ctx context.Context, in *UpdateTenantAppStatusRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.UpdateTenantAppStatus(ctx, in, opts...)
}

func (m *defaultAccessService) UpdateAppQuota(ctx context.Context, in *UpdateAppQuotaRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.UpdateAppQuota(ctx, in, opts...)
}

func (m *defaultAccessService) CheckIpBan(ctx context.Context, in *CheckIpBanRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := accesspb.NewAccessServiceClient(m.cli.Conn())
	return client.CheckIpBan(ctx, in, opts...)
}
