// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"xsonar/apps/gateway-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/search/trending",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/search/trends",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/search/tweets",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tweets/by-ids",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tweets/detail",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tweets/replies",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tweets/timeline",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/by-id",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/by-ids",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/by-username",
				Handler: serverCtx.Bridge.HandleProxy,
			},
		},
	)
}
