// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1

package handler

import (
	"net/http"

	"xsonar/apps/gateway-api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/v1/communities",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/lists",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/search/box",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/search/entertainment",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/search/explore",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/search/news",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/search/sports",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/search/trending",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/search/trends",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/search/tweets",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tweets/by-ids",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tweets/brief",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tweets/detail",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tweets/favoriters",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tweets/quotes",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tweets/replies",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tweets/retweeters",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/tweets/timeline",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/account-analytics",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/articles-tweets",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/by-id",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/by-ids",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/by-username",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/followers",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/followings",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/highlights",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/likes",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/mentions-timeline",
				Handler: serverCtx.Bridge.HandleProxy,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/users/username-changes",
				Handler: serverCtx.Bridge.HandleProxy,
			},
		},
	)
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/v1/collector/tasks/periodic",
				Handler: serverCtx.Bridge.HandleCreatePeriodicCollectorTask,
			},
			{
				Method:  http.MethodPost,
				Path:    "/v1/collector/tasks/range",
				Handler: serverCtx.Bridge.HandleCreateRangeCollectorTask,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/collector/tasks/:id",
				Handler: serverCtx.Bridge.HandleGetCollectorTask,
			},
			{
				Method:  http.MethodGet,
				Path:    "/v1/collector/tasks/:id/runs",
				Handler: serverCtx.Bridge.HandleListCollectorTaskRuns,
			},
		},
	)
}
