// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: provider.proto

package providerservice

import (
	"context"

	"xsonar/pkg/proto/providerpb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ExecutePolicyRequest       = providerpb.ExecutePolicyRequest
	HealthCheckProviderRequest = providerpb.HealthCheckProviderRequest
	JsonResponse               = providerpb.JsonResponse

	ProviderService interface {
		ExecutePolicy(ctx context.Context, in *ExecutePolicyRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		HealthCheckProvider(ctx context.Context, in *HealthCheckProviderRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	}

	defaultProviderService struct {
		cli zrpc.Client
	}
)

func NewProviderService(cli zrpc.Client) ProviderService {
	return &defaultProviderService{
		cli: cli,
	}
}

func (m *defaultProviderService) ExecutePolicy(ctx context.Context, in *ExecutePolicyRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := providerpb.NewProviderServiceClient(m.cli.Conn())
	return client.ExecutePolicy(ctx, in, opts...)
}

func (m *defaultProviderService) HealthCheckProvider(ctx context.Context, in *HealthCheckProviderRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := providerpb.NewProviderServiceClient(m.cli.Conn())
	return client.HealthCheckProvider(ctx, in, opts...)
}
