// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.1
// Source: policy.proto

package policyservice

import (
	"context"

	"xsonar/pkg/proto/policypb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	BindAppPoliciesRequest      = policypb.BindAppPoliciesRequest
	CheckAppPolicyAccessRequest = policypb.CheckAppPolicyAccessRequest
	JsonResponse                = policypb.JsonResponse
	ListPoliciesRequest         = policypb.ListPoliciesRequest
	PublishPolicyConfigRequest  = policypb.PublishPolicyConfigRequest
	ResolvePolicyRequest        = policypb.ResolvePolicyRequest

	PolicyService interface {
		ResolvePolicy(ctx context.Context, in *ResolvePolicyRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		CheckAppPolicyAccess(ctx context.Context, in *CheckAppPolicyAccessRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		PublishPolicyConfig(ctx context.Context, in *PublishPolicyConfigRequest, opts ...grpc.CallOption) (*JsonResponse, error)
		BindAppPolicies(ctx context.Context, in *BindAppPoliciesRequest, opts ...grpc.CallOption) (*JsonResponse, error)
	}

	defaultPolicyService struct {
		cli zrpc.Client
	}
)

func NewPolicyService(cli zrpc.Client) PolicyService {
	return &defaultPolicyService{
		cli: cli,
	}
}

func (m *defaultPolicyService) ResolvePolicy(ctx context.Context, in *ResolvePolicyRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := policypb.NewPolicyServiceClient(m.cli.Conn())
	return client.ResolvePolicy(ctx, in, opts...)
}

func (m *defaultPolicyService) CheckAppPolicyAccess(ctx context.Context, in *CheckAppPolicyAccessRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := policypb.NewPolicyServiceClient(m.cli.Conn())
	return client.CheckAppPolicyAccess(ctx, in, opts...)
}

func (m *defaultPolicyService) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := policypb.NewPolicyServiceClient(m.cli.Conn())
	return client.ListPolicies(ctx, in, opts...)
}

func (m *defaultPolicyService) PublishPolicyConfig(ctx context.Context, in *PublishPolicyConfigRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := policypb.NewPolicyServiceClient(m.cli.Conn())
	return client.PublishPolicyConfig(ctx, in, opts...)
}

func (m *defaultPolicyService) BindAppPolicies(ctx context.Context, in *BindAppPoliciesRequest, opts ...grpc.CallOption) (*JsonResponse, error) {
	client := policypb.NewPolicyServiceClient(m.cli.Conn())
	return client.BindAppPolicies(ctx, in, opts...)
}
